rudderlabs/rudder-sdk-js

- analytics.js
The console gets spammed with `anonymousId: ...`
I just replaced `console.log` with `logger.debug` so that it's only logged during development
> Replace console.log with logger.debug

- utils/RudderContext.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/36)
> remove default_ip

- package.json
- release.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/38)
> add missing dependency

- analytics.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/39)
> add page prop to context and autotrack enabled from load option

- analytics.js
- integrations/Lotame/browser.js
- tests/html/script-test.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/46)
> add callbacks to method names globally

- integrations/GoogleTagManager/browser.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/59)
> added empty page call handling for GTM

- integrations/GoogleTagManager/browser.js
Reverts rudderlabs/rudder-sdk-js#59
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/61)
> Revert "added empty page call handling for GTM"

- integrations/GoogleAds/browser.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/67)
> GoogleAds Device Mode - empty page call handling

- dist/browser.js
- integrations/GA/browser.js
- integrations/GoogleTagManager/browser.js
- tests/html/script-test.html
- utils/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/70)
> Ga change work in progress

- integrations/GA/browser.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/84)
> backward compatibility

- utils/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/86)
> remove browser check

- dist/rudder-sdk-js/package.json
- integrations/GA/browser.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/89)
> mater --> production

- dist/rudder-sdk-js/index.d.ts
- dist/rudder-sdk-js/package.json
- package.json
- utils/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/90)
> fix - pathname for canonical url

- analytics.js
- utils/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/93)
> Handling version and module type in sourceconfigurl as user input

- tests/html/autotrack-test.html
- utils/autotrack.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/96)
> Changes for not tracking sensitive data

- analytics.js
- utils/EventRepository.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/100)
> Missing writekey

- analytics.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/102)
> Send the events to server/destination that are made only after load call

- analytics.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/104)
> Error handling if rudderanalytics is not initialized in script

- analytics.js
- dist/rudder-sdk-js/index.js
- jest.config.js
- package.json
- utils/storage/cookie.js
- utils/storage/storage.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/101)
> Encrypt values

- .babelrc
- .eslintrc.json
- integrations/Optimizely/browser.js
- integrations/Optimizely/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/109)
> Optimizely Web

- dist/browser.js
- dist/rudder-sdk-js/index.js
- dist/rudder-sdk-js/package.json
- integrations/FacebookPixel/browser.js
- jest.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/107)
> addressed issue related to script loading for cordova

- integrations/Chartbeat/browser.js
- integrations/Kissmetrics/browser.js
- integrations/VWO/browser.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/108)
> added https in scriptload for VWO,kissmetrics,chartbeat

- analytics.js
- utils/storage/storage.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/110)
> Fix: Group traits after reset

- integrations/Chartbeat/browser.js
- integrations/Kissmetrics/browser.js
- integrations/VWO/browser.js
Reverts rudderlabs/rudder-sdk-js#108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/111)
> Revert "added https in scriptload for VWO,kissmetrics,chartbeat"

- integrations/Bugsnag/browser.js
- integrations/Bugsnag/index.js
- integrations/GA/index.test.js
- integrations/GA/node.js
- integrations/GoogleAds/node.js
- integrations/Hotjar/node.js
- integrations/HubSpot/node.js
- integrations/index.js
- integrations/integration_cname.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/114)
> added bugsnag destination

- analytics.js
- integrations/Fullstory/browser.js
- integrations/Fullstory/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
- package.json
references #115
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/116)
> copy changes from fullstory branch

- analytics.js
- package.json
- utils/EventRepository.js
- utils/storage/cookie.js
- utils/storage/storage.js
- utils/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/119)
> Fix: encrypted cookie

- README.md
- analytics.js
- dist/rudder-sdk-js/index.js
- dist/rudder-sdk-js/package.json
- utils/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/127)
> Add merge event support

- analytics.js
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/128)
> add query parse logic from url and send events ---> Production

- integrations/ScriptLoader.js
- integrations/TVSquared/browser.js
- integrations/TVSquared/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/120)
> added tvsquared as destination

- integrations/ScriptLoader.js
- integrations/TVSquared/browser.js
- integrations/TVSquared/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/134)
> TVSquared destination

- package.json
- rollup.config.js
- stats.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/133)
> add visualizer

- dist/rudder-sdk-js/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/140)
> Npm rebase

- integrations/HubSpot/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/149)
> Forced hubspot to load on https

- analytics.js
- package.json
- utils/EventRepository.js
> This has changes for adding campaign information and support XHR queue config during load
> Fix 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/148)
> merge campaign and configurable queue

- analytics.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/151)
> add check for options

- integrations/Amplitude/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/158)
> Amplitude - Code refactoring

- integrations/Amplitude/browser.js
- integrations/Amplitude/test/test_amplitude.html
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/159)
> Amplitude - code refactoring and test file add

- integrations/Amplitude/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/161)
> Added revenue_type key

- integrations/Amplitude/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/162)
> Amplitude - added version name

- integrations/Amplitude/browser.js
- package.json
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/163)
> Production <- staging

- integrations/Lytics/browser.js
- integrations/Lytics/index.js
- integrations/Lytics/test/script-test-lytics.html
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/165)
> added lytics destination

- integrations/Pendo/browser.js
- integrations/Pendo/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
- utils/utils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/167)
> pendo-sdk/commit for staging branch

- integrations/Amplitude/browser.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/168)
> add intg name

- integrations/Pendo/browser.js
- integrations/Pendo/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
- package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/175)
> add files from staging for Pendo release

- integrations/GA4/browser.js
- integrations/GA4/utils.js
- tests/html/script-test.html
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/177)
> GA4 Bug fixes

- integrations/GA4/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/179)
> GA4 Bug fixes- flattening track call json payload

- integrations/GA4/browser.js
…View is false
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/180)
> GA4 Bug fixes- page view will not trigger with identify call when blockPageView flag is true.

- analytics.js
- utils/constants.js
- utils/utils.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/184)
> Reserved keys

- utils/utils.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/186)
> add lowercase check

- integrations/index.js
- package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/185)
> Production <-- staging

- integrations/FacebookPixel/browser.js
The script fails to submit purchase events due to this error
> Fix [#188 ]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/190)
> product is not defined

- README.md
- analytics.js
- utils/linker/base64decoder.js
- utils/linker/crc32.js
- utils/linker/index.js
- utils/linker/userLib.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/193)
> Amp linker

- dist/rudder-sdk-js/README.md
- dist/rudder-sdk-js/index.js
- dist/rudder-sdk-js/package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/195)
> Production merge

- analytics.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/197)
> Fix: Querystring api

- analytics.js
- integrations/GA/browser.js
- integrations/ScriptLoader.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/204)
> improve logs

- analytics.js
- utils/storage/storage.js
- utils/utils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/213)
> Persistence of initial page properties

- .babelrc
- package.json
- rollup.config.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/214)
> Babel transform plugin for object assign

- integrations/Klaviyo/browser.js
- utils/utils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/215)
> klaviyo - minor fixes

- integrations/Klaviyo/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/218)
> klaviyo support of email as primary

- analytics.js
- utils/storage/storage.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/221)
> pull changes from other PR and changes to storage for cookie domain

- analytics.js
- package.json
- utils/storage/storage.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/223)
> Custom domain

- integrations/Clevertap/browser.js
- utils/utils.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/225)
> Clevertap Post test fixes

- integrations/Clevertap/browser.js
- utils/utils.js
> Post testing fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/227)
> Legacy support fixes Clevertap

- analytics.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/228)
> getUserTraits

- analytics.js
- utils/storage/storage.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/237)
> Reset anonId based on flag

- analytics.js
- utils/utils.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/238)
> change page defaults

- utils/utils.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/239)
> add location.href as page defaults

- integrations/PinterestTag/browser.js
- integrations/PinterestTag/index.js
- integrations/PinterestTag/propertyMappingConfig.js
- integrations/PinterestTag/test/input.js
- integrations/PinterestTag/test/output.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
- utils/utils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/242)
> Pinterest Tag SDK commit

- integrations/PinterestTag/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/244)
> Event ordering issues fixed

- integrations/FacebookPixel/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/247)
> added check for product array in fb pixel

- integrations/FacebookPixel/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/251)
> fb pixel custom event fix

- integrations/FacebookPixel/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/252)
> changed logic for payload for custom events

- integrations/FacebookPixel/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/256)
> refactor +bug fix fb pixel

- utils/RudderContext.js
- utils/RudderInfo.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/257)
> added and fixed screen info for context.screen for device mode

- integrations/AdobeAnalytics/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/258)
> added proxy url for loading aa sdks

- integrations/CustomerIO/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/260)
> removed adding of created_at if not present in traits customer io

- README.md
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/261)
> Production staging

- integrations/Heap/browser.js
- integrations/Heap/index.js
- integrations/Heap/util.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
- integrations/utils/commonUtils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/265)
> developed heap web device mode

- integrations/Heap/browser.js
- integrations/Heap/index.js
- integrations/Heap/util.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
- integrations/utils/commonUtils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/268)
> Heap device mode

- integrations/Lytics/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/269)
> added support for name

- integrations/RedditPixel/browser.js
- integrations/RedditPixel/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
add RedditPixel device-mode integration
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/272)
> Reddit Pixel integration

- integrations/GoogleAds/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/286)
> added three additional settings

- integrations/Mixpanel/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/285)
> Mixpanel added support for cookie configs device mode

- integrations/GoogleAds/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/288)
> added default value for additional settings

- integrations/Criteo/browser.js
- integrations/Criteo/index.js
- integrations/Criteo/utils.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/279)
> Criteo integrations

- integrations/Mixpanel/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/289)
> Mixpanel fix for persistance name

- integrations/Mixpanel/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/290)
> Mixpanel fix for persistance name none

- integrations/Criteo/browser.js
- integrations/Criteo/utils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/291)
> Criteo : refactored code

- integrations/GoogleTagManager/browser.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/292)
> Added traits support to GTM

- integrations/Lytics/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/284)
> Lytics typo

- integrations/Qualtrics/browser.js
- integrations/Qualtrics/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/294)
> Qualtrics Integration

- integrations/Drip/browser.js
- integrations/Drip/index.js
- integrations/Drip/utils.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/295)
> Drip Integration

- integrations/Drip/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/296)
> Drip Integration - updates

- integrations/Qualtrics/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/297)
> Qualtrics: Ternary condition Edit

- integrations/Drip/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/299)
> Drip - update

- integrations/AdobeAnalytics/heartbeatHandle.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/298)
> set ovp for AA from properties (dr.dk)

- integrations/Qualtrics/browser.js
- integrations/Qualtrics/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/300)
> Qualtrics integrations js sdk

- integrations/Drip/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/301)
> Drip - Identify call update

- integrations/Braze/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/306)
> added allowUserSuppliedJavascript

- integrations/FacebookPixel/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/311)
> add sha256 missed import

- integrations/FacebookPixel/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/312)
> update sha256 value for fb_pixel

- integrations/FacebookPixel/browser.js
- integrations/SnapPixel/browser.js
- integrations/SnapPixel/index.js
- integrations/SnapPixel/util.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/310)
> Snap Pixel Integration

- integrations/ProfitWell/browser.js
- integrations/ProfitWell/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/323)
> Profitwell Integration

- integrations/ProfitWell/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/326)
> Profitwell device-mode update

- integrations/ProfitWell/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/327)
> Profitwell device-mode - Issue

- integrations/ProfitWell/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/330)
> move marketing tracking to identify

- integrations/ProfitWell/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/331)
> Profitwell update: add cond. check

- integrations/ProfitWell/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/332)
> change log level to debug

- integrations/Sentry/browser.js
- integrations/Sentry/index.js
- integrations/Sentry/utils.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/335)
> Sentry integration

- integrations/Sentry/browser.js
- integrations/Sentry/utils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/337)
> Sentry Integrations

- integrations/Sentry/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/339)
> update scriptloader id

- integrations/Sentry/browser.js
- integrations/Sentry/index.js
- integrations/Sentry/utils.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/341)
> Sentry production

- integrations/Sentry/utils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/342)
> fix bug on sentry rewriteFrames

- integrations/Sentry/utils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/343)
> edit in rewriteFrames for ForEach

- integrations/integration_cname.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/345)
> fixed the type but shouldn't affect any previous or future additions ADOBE_ANALYTICS

- integrations/QuantumMetric/browser.js
- integrations/QuantumMetric/index.js
- integrations/index.js
- integrations/integration_cname.js
- package.json
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/349)
> Quantum metric integration

- dist/rudder-sdk-js/package.json
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/351)
> NPM package v1.0.20 published

- integrations/GA4/ECommerceEventConfig.js
- integrations/GA4/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/192)
> Added Group call support for GA4

- README.md
- dist/rudder-sdk-js/README.md
> Refreshed the readme content as per the latest doc changes.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/350)
> Updated structure and revamped content

- dist/rudder-sdk-js/index.d.ts
- package.json
> Boolean type added in apiObject and apiOptions interfaces in type declaration file.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/364)
> Ts declaration fix

- dist/rudder-sdk-js/package.json
- package.json
> Package version updated in the right place
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/365)
> package version updated

- integrations/Posthog/browser.js
- utils/utils.js
> Included check for trailing slashes for instance url and removing it if present.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/363)
> Bug : removing the trailing slashes in instance url for Posthog

- dist/rudder-sdk-js/package.json
- package.json
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/368)
> Bumped version

- CONTRIBUTING.md
- README.md
> Added a contributor's guide for the users to contribute to this repository.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/370)
> Added CONTRIBUTING.MD

- dist/rudder-sdk-js/index.d.ts
- dist/rudder-sdk-js/package.json
- package.json
> Support for Array of string, number, boolean, object added in ts declaration 
> Fix [#371 ]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/372)
> Bug: Support for advanced combinations of parameters in objects missing in TS declaration file

- dist/rudder-sdk-js/package.json
- integrations/Amplitude/browser.js
- package.json
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/375)
> AM Segment Type Page Event Name Support Update

- dist/rudder-sdk-js/index.d.ts
- dist/rudder-sdk-js/package.json
- package.json
> few minor changes in the ts declaration file
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/373)
> Bug: Incomplete data type definitions

- dist/rudder-sdk-js/index.d.ts
- dist/rudder-sdk-js/package.json
- package.json
> Bump the version from 1.2.7 to 1.2.8
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/376)
> Version bump

- dist/rudder-sdk-js/package.json
- package.json
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/382)
> Version bump for release

- integrations/GoogleOptimize/browser.js
- integrations/GoogleOptimize/index.js
- integrations/ScriptLoader.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
New device mode destinaton google optimize.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/379)
> Feat : Destination Google optimize

- integrations/TVSquared/browser.js
> add check for deleting custom variable
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/380)
> TVSquared - fix: add check for deleteCustomVariable

- integrations/TVSquared/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/387)
> production-staging -> production (#380)

- integrations/INTERCOM/browser.js
- integrations/TVSquared/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/391)
> production-staging -> production

- integrations/GoogleAds/browser.js
> add dynamic remarketing
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/394)
> Google Ads - feat: add dynamic remarketing

- README.md
> Small text added in the autotrack depreciation note.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/393)
> Autotrack depreciation note modified

- integrations/FacebookPixel/browser.js
> for handling duplicate pixel
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/396)
> FB Pixel - feat: Handle duplicate pixel

- integrations/Klaviyo/browser.js
- integrations/Klaviyo/util.js
This PR contains changes that will support ecom events for track calls.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/388)
> Enhancement Klaviyo : Introducing Ecom Events for Track calls

- dist/rudder-sdk-js/package.json
- package.json
> Upgraded the npm package set-value to it’s latest version.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/397)
> Set-value dependency upgrade

- analytics.js
> Support for secure cookie flag
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/398)
> add secure cookie flag

- analytics.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/403)
> Removed the usage of loadash module to reduce the SDK size

- analytics.js
- utils/utils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/392)
> writekey added in source config API

- analytics.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/406)
> Modified cookieConsent class variable to local variable

- utils/storage/storage.js
> Error handling when both of the storage is unavailable 
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/407)
> Error handling when both of the storage is unavailable 

- analytics.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/409)
> logic modified for checking cookieConsentOptions is present or not

- README.md
- analytics.js
- buildspec.staging.yaml
- integrations/GA/index.js
- integrations/GoogleAds/index.js
- integrations/Hotjar/index.js
- integrations/HubSpot/index.js
- package.json
- utils/utils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/412)
> Miscellaneous updates re: v1.1

- integrations/GA/index.js
- integrations/GoogleAds/index.js
- integrations/Hotjar/index.js
- integrations/HubSpot/index.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/420)
> fixed export statement issue

- analytics.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/423)
> Fixed Integration loading issue when one is failed to load

- integrations/ScriptLoader.js
Adding script inside head if head is available
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/425)
> Google Opitmize bugFix:  Adding script inside head if head is available

- dist/rudder-sdk-js/package.json
- integrations/Fullstory/browser.js
- package.json
This feature will help us to track a user who is coming from a different domain and identified by fullstory already.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/426)
> Fullstory cross domain user tracking support.

- integrations/ScriptLoader.js
added index at the end of head
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/427)
> Scriptloader Bugfix: Google optimize

- buildspec.staging.yaml
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/429)
> staging yml file updated

- buildspec.staging.yaml
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/430)
> staging pipeline update

- integrations/Posthog/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/436)
> posthog loaded function 

- .gitignore
- analytics.js
- integrations/GoogleTagManager/browser.js
- integrations/PinterestTag/propertyMappingConfig.js
- integrations/Posthog/browser.js
- utils/utils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/437)
> staging -> production

- integrations/GoogleTagManager/browser.js
- integrations/integration_cname.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/438)
> GTM: Fixed the different cnames to GTM (similar with control-plane name)

- integrations/Amplitude/browser.js
Deleting duplicate fields price, quantity and productId for revenue payload.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/443)
> BugFix Amplitude : Deleting duplicate fields in revenue payload

- __tests__/camelcase.test.js
- analytics.js
- integrations/Fullstory/browser.js
- package.json
- utils/camelcase.js
- utils/constants.js
- utils/utils.js
* IE support related changes
* logger.debug removed
* code cleanup
* set-value package replaced with simple logic
* polyfill url added in constant
* test case for camelcase logic
Co-authored-by: Moumita Mandal <moumita@rudderstack.com>
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/450)
> Staging -> Production IE support

- .gitignore
- analytics.js
- dist/rudder-sdk-js/package.json
- integrations/GoogleTagManager/browser.js
- integrations/PinterestTag/propertyMappingConfig.js
- integrations/Posthog/browser.js
- package.json
- utils/utils.js
* IE support related changes
* logger.debug removed
* code cleanup
* set-value package replaced with simple logic
* polyfill url added in constant
* test case for camelcase logic
Co-authored-by: Moumita Mandal <moumita@rudderstack.com>
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/451)
> v1 staging --> v1.1 staging [IE support related changes (#449)]

- dist/rudder-sdk-js/package.json
- package.json
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/462)
> version bumped

- integrations/VWO/browser.js
- integrations/VWO/index.js
> added load-integration flag, logger cleanup
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/463)
> VWO: added load-integration flag, logger cleanup

- analytics.js
Added a function getUserId() to display the User Id 
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/454)
> Added a new function to retrieve UserId

- integrations/GA/browser.js
> Added Prefix and Suffix to name and category
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/470)
> added prefix and suffix to name and category

- integrations/GA360/browser.js
- integrations/GA360/constants.js
- integrations/GA360/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Added GA 360 as a new integration.
- The base GA 360 class inherited all the properties from the GA class.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/473)
> GA 360 integration

- integrations/GA360/browser.js
- integrations/GA360/index.js
- utils/config_to_integration_names.js
> Changes related to GA 360 in v1.1
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/474)
> GA 360 added in v1.1

- integrations/GA360/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/475)
> updated default import to named import

- integrations/FacebookPixel/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/479)
> Removing discrepency with cloud mode for Facebook Pixel 

- integrations/FacebookPixel/browser.js
Here we are upgrading the js-sdk for facebook pixel as there are some discrepancy with the cloud mode mappings.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/480)
> Removing discrepancy with cloud mode Facebook_Pixel. 

- integrations/FacebookPixel/utils.js
> Added checks for `event_id` values.
> 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/492)
> FB Pixel utils: Added validation for event_id values

- integrations/SnapPixel/browser.js
> Event name is integer or special character
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/498)
> Snap Pixel :: bug fix - event name is integer

- integrations/FacebookPixel/browser.js
`event_id` was wrongly mapped and is updated to `eventID`
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/501)
> Bug fix (fb_pixel): wrongly mapped event_id 

- README.md
> Updated correct links for the data plane URL and source write key doc references.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/521)
> Broken URLs hotfix

- integrations/Braze/browser.js
Adding support for dynamic data center for EU
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/541)
> Fix. Braze device mode integration

- utils/JSFileLoader.js
Added an improved script loader.
This is not meant for immediate use in the SDK.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/524)
> Patch: Improved script loader utility

- utils/RudderMessage.js
Removed unused "action" field in RudderMessage
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/525)
> Patch: Removed unused 'action' field in RudderMessagge

- __tests__/camelcase.test.js
- __tests__/script.test.js
- analytics.js
- utils/camelcase.js
- utils/constants.js
- utils/utils.js
Removed unused constants and renamed them appropriately.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/532)
> Patch: Removed unused constants

- __tests__/camelcase.test.js
- __tests__/script.test.js
- analytics.js
- jest.config.js
- package.json
- utils/camelcase.js
Refactored the unit test suite. 
Additionally, updated the `getUserId` API to directly return the class variable value at it'll always contain the latest value.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/531)
> Patch: Refactor the unit test suite

- integrationBuildScript.js
Updated `integrationBuildScript.js` to build multiple integration SDKs simultaneously. It only uses (maximum number of CPUs available - 1) number of simultaneous processes at any given time.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/530)
> Feat: Added concurrency to integrationBuildScript.js

- utils/EventRepository.js
- utils/beaconQueue.js
Relocated `beaconQueue.js` file to make it consistent with `xhrModule.js`.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/529)
> Patch: Relocated beacon queue module

- analytics.js
- dist/rudder-sdk-js/index.d.ts
Added group APIs.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/527)
> Feat: Added group APIs

- .size-limit.js
- integrations/DCMFloodlight/index.js
- utils/config_to_integration_names.js
- utils/integration_cname.js
> make v1.1 architectural changes
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/545)
> feature(integration): DCM - make v1.1 architectural changes

- analytics.js
- utils/logUtil.js
- handled undefined integration obj error
- Updated console APIs in logUtil
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/551)
> Fix: handled undefined integration obj error

- integrations/Matomo/browser.js
- integrations/Matomo/constants.js
- integrations/Matomo/index.js
- integrations/Matomo/util.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
- integrations/utils/commonUtils.js
- utils/constants.js
> Onboarding Matomo Device Mode Integration
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/550)
> feature(new integration): Matomo web Device mode integration onboarding

- integrations/Vero/index.js
- utils/config_to_integration_names.js
- utils/integration_cname.js
> Vero web Device mode integration onboarding-production
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/556)
> feature(new integration): Vero web Device mode integration onboarding-production

- .size-limit.js
- integrations/Matomo/index.js
- utils/config_to_integration_names.js
- utils/integration_cname.js
> Onboarding Matomo in the `production` branch
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/555)
> feature(new integration): Matomo web Device mode integration onboarding-production

- integrations/Vero/browser.js
> Vero tags object checked
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/559)
> bugfix(vero): Vero tags object checked

- integrations/Matomo/browser.js
- integrations/Matomo/util.js
- integrations/utils/commonUtils.js
> Matomo bugfix -`production-staging` branch
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/561)
> bugfix(non CFD): Matomo production PR

- buildspec.prod.yaml
> Fixed invalidation bug in prod buildspec file.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/563)
> Invalidation bug in prod buildspec file

- integrations/SnapPixel/browser.js
- integrations/SnapPixel/util.js
> Update init, Identify and Track function, also added option of `client_deduplication_id` to take from key mentioned by the user or from messageId.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/571)
> bugfix[SnapPixel]: update init, identify and track call

- analytics.js
- utils/utils.js
Renamed and refactored the `checkSDKUrl` utility method.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/580)
> refactor: rename checkSDKUrl

- analytics.js
> Minor bug fix in integrationSDKLoaded fn
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/583)
> Minor bug fix in integrationSDKLoaded fn

- metrics/error-report/Bugsnag.js
- Validate the Bugsnag error filtering logic
- Add error handling around it
- Change maxEvents to 100
- If the request URL is 127.0.0.1 then set releaseStage as dev.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/581)
> Enhancement in  Bugsnag error filtering

- analytics.js
- metrics/error-report/Bugsnag.js
> New parameter added in scriptLoader call
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/596)
> New parameter added in scriptLoader call

- integrations/Mouseflow/browser.js
- integrations/Mouseflow/constants.js
- integrations/Mouseflow/index.js
- integrations/Mouseflow/utils.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Mouseflow - new Integration for web device mode.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/590)
> feature/mouseflow: new Integration Onboarding

- integrations/Criteo/browser.js
- integrations/Criteo/constants.js
- integrations/utils/commonUtils.js
- in browser.js file of criteo destination, in track call, logic added in order to map events
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/595)
> feature(event filtering): criteo onetag

- .size-limit.js
- integrations/Mouseflow/index.js
- utils/config_to_integration_names.js
- utils/integration_cname.js
> Onboarding new-integrations, web device mode
- [✅] New feature (non-breaking change that adds functionality)
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/599)
> feature/mouseflow: Onboarding new-integrations, web device mode

- integrations/FacebookPixel/browser.js
> `content_id` and `contents` array is not mandatory. We were throwing error for this. This got edited in cloud mode
- [] New feature (non-breaking change that adds functionality)
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/594)
> Feature(Fb Pixel): Compatibilty with cloud mode

- integrations/Rockerbox/index.js
- utils/client_server_name.js
- utils/config_to_integration_names.js
- utils/integration_cname.js
> Onboarding Rockerbox
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/609)
> feature/new integration: Onboarding rockerbox for v1.1

- integrations/SnapEngage/browser.js
- integrations/SnapEngage/util.js
> adding the loader dataset attribute to the script tag
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/615)
> feature(enhancement): adding the loader dataset attribute to the script tag

- integrations/ConvertFlow/utils.js
>correcting typo in event name
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/616)
> bugfix(ConvertFlow): correcting typo in event name

- integrations/VWO/browser.js
> Relocate loadIntegration check in VWO to a non-blocker check.
> Add JS SDK loadIntegration support for VWO
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/614)
> Fix: VWO loadintegration option

- integrations/VWO/browser.js
Reverts rudderlabs/rudder-sdk-js #614
To be deferred until all customers are informed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/618)
> Revert "Fix: VWO loadintegration option" changes

- .size-limit.js
- integrations/SnapEngage/index.js
- utils/client_server_name.js
- utils/config_to_integration_names.js
- utils/integration_cname.js
> Onboarding SnapEngage-v1.1
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/620)
> feature(new integration): SnapEngage web Device mode integration onboarding-v1.1

- dist/rudder-sdk-js/index.d.ts
> Type declaration updated
> Fix [#621 ]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/625)
> Type declaration updated

- __tests__/script.test.js
- analytics.js
- integrations/Mixpanel/browser.js
- integrations/VWO/browser.js
- utils/beaconQueue.js
- utils/xhrModule.js
Incorporated eslint suggestions.
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/628)
> refactor: incorporate eslint suggestions

- integrations/SnapPixel/browser.js
>update cookie check conditions
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/626)
> fix(snappixel): cookie check

- integrations/INTERCOM/browser.js
- utils/utils.js
Putting support of flattenJson to add object type properties in track call.
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/629)
> Feature(Intercom): Adding support of flattenJson in track call properties.

- integrations/Rockerbox/browser.js
> Add anonymousId to identify,Track and Page calls
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/636)
> feat (rockerbox): add anonymousId for all calls

- integrations/Shynet/browser.js
- integrations/Shynet/constants.js
- integrations/Shynet/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Shynet new destination onboarding.
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/630)
> feature(new integration): shynet-destination

- .size-limit.js
- integrations/LiveChat/index.js
- utils/client_server_name.js
- utils/config_to_integration_names.js
- utils/integration_cname.js
> onboarding LiveChat v1.1
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/640)
> feature(new integration): LiveChat web Device mode integration onboarding-v1.1

- .size-limit.js
- integrations/Shynet/index.js
- utils/client_server_name.js
- utils/config_to_integration_names.js
- utils/integration_cname.js
Shynet Destination .
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/641)
> Feature(new integration): Shynet device mode onboarding v1.1

- integrations/QuoraPixel/browser.js
- integrations/QuoraPixel/constants.js
- integrations/QuoraPixel/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Quora Pixel Web Device Mode Destination Onboarding
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/647)
> feat(new integration): quora pixel device mode destination onboarding

- integrations/RollBar/browser.js
- integrations/RollBar/constants.js
- integrations/RollBar/index.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> onboarding Rollbar
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/646)
> feature(new integration): RollBar web Device mode integration onboarding

- integrations/LinkedInInsightTag/browser.js
> support for event-specific conversion
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/648)
> feat(LinkedIn Insights Tag): add support for event-specific conversion

- .size-limit.js
- integrations/QuoraPixel/index.js
- utils/client_server_name.js
- utils/config_to_integration_names.js
- utils/integration_cname.js
> Quora Pixel Device Mode Destination Onboarding
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/653)
> feature(new integration): quora pixel destination onboarding v1.1

- .size-limit.js
- integrations/RollBar/index.js
- utils/client_server_name.js
- utils/config_to_integration_names.js
- utils/integration_cname.js
>onboarding RollBar
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/652)
> feature(new integration): Onboarding RollBar Destination v1.1

- integrations/Woopra/index.js
- utils/client_server_name.js
- utils/config_to_integration_names.js
- utils/integration_cname.js
> Feature new integration:  Woopra Destination
- [ + ] New feature (non-breaking change that adds functionality)
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/651)
> feature(new integration): Onboarding Woopra Destination

- integrations/QuoraPixel/browser.js
> Add warn log for track call
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/660)
> feat(quora pixel): add warn logs for track API

- integrations/PinterestTag/browser.js
… added
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/659)
> feat(integration): add multiplexing support to Pinterest Tag

- integrations/Engage/browser.js
- integrations/Engage/constants.js
- integrations/Engage/index.js
- integrations/Engage/utils.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
- utils/utils.js
> Onboarding new destination Engage
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/662)
> feat(new integration): Onboarding Engage Device Mode

- .size-limit.js
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/674)
> chore: update size limit

- .size-limit.js
- integrations/Engage/browser.js
- integrations/Engage/index.js
- utils/client_server_name.js
- utils/config_to_integration_names.js
- utils/integration_cname.js
> Onboarding Engaging Destination
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/672)
> feat(new integration): Engage - onboard integration

- integrations/June/browser.js
> Set log level in constructor
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/675)
> feat(june): set log level

- integrations/Braze/browser.js
We are missing validation of userId in Braze web device mode. We have to add a button in the dashboard, it will help us to decide if we want to track the anonymous users or not. Apart from that, we have to update the page call as well. If the user doesn’t provide any page name we will add the name as page view .
- [-] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/669)
> feat: improved page/track calls braze

- integrations/YandexMetrica/browser.js
- integrations/YandexMetrica/constants.js
- integrations/YandexMetrica/index.js
- integrations/YandexMetrica/utils.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> onboarding yandex.metrica destination
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/671)
> feat(new-integration): onboarding yandex.metrica destination

- buildspec.dev.yaml
- buildspec.prod.yaml
- buildspec.staging.yaml
> Node version updated in buildspec files
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/683)
> chore(buildspec): node version updated

- integrations/Posthog/browser.js
> posthog group call support
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/688)
> feat: posthog group call support

- package-lock.json
- package.json
- service-worker/index.js
- tests/chrome-extension/background-script/rudderAnalytics.js
Remove non tree shaked code of utils from service worker bundle that breaks in service worker
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/711)
> fix: remove non tree shaked code of utils from service worker bundle

- integrations/Qualaroo/browser.js
- integrations/Qualaroo/constants.js
- integrations/Qualaroo/index.js
- integrations/Qualaroo/utils.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Onboarding Qualaroo device mode destination
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/715)
> feat(new integration): onboarding qualaroo device mode destination

- .size-limit.js
- integrations/Podsights/index.js
- utils/client_server_name.js
- utils/config_to_integration_names.js
- utils/integration_cname.js
> Onboarding new destination
- [ ✅] New feature (non-breaking change that adds functionality)
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/721)
> feat(Podsights): Onboarding new destination

- service-worker/index.js
- tests/chrome-extension/content-script/foreground.js
- utils/RudderMessage.js
- Removed timestamp from messageId
- Updated service worker to use only uuid as messageId
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/737)
> feat(core): remove timestamp from message id 

- utils/beaconQueue.js
> Fixed illegal invocation bug of sendBeacon
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/738)
> fix(core): illegal invocation of sendBeacon

- utils/storage/beaconQueue.js
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/735)
> fix: illegal invocation issue for sendBeacon

- integrations/Satismeter/browser.js
- integrations/Satismeter/constants.js
- integrations/Satismeter/index.js
- integrations/Satismeter/util.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
> Onboarding a new destination SatisMeter with Identify and Track Call. Have made a call with writeKey only inside init(), to help to record the survey responses on the destination even without identify call i.e. as anonymous user. 
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/732)
> feat(destination): onboard satismeter

- integrations/Braze/browser.js
- package.json
> Here, it will add dedup support for identify call in Braze
- [✅] New feature (non-breaking change that adds functionality)
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/728)
> feat(destination): add dedup support for identify call in Braze

- integrations/BingAds/browser.js
> Microsoft updated the syntax for the javascript UET tracking library. Ref [doc](https://help.ads.microsoft.com/#apex/ads/en/56916/2-500). So made changes in bind ads destination reflecting the same.
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/740)
> fix(destination): updated bing ads syntax as per the updated Microsoft's syntax

- integrations/Axeptio/browser.js
- integrations/Axeptio/constants.js
- integrations/Axeptio/index.js
- integrations/Axeptio/utils.js
- integrations/client_server_name.js
- integrations/index.js
- integrations/integration_cname.js
Onboard new web device mode destination Axeptio
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/743)
> feat/axeptio: onboard web device mode destination axeptio

- .github/workflows/deploy-prod-v1.yml
- .github/workflows/deploy-staging-v1.yml
Add code build and deploy equivalents of aws in github actions for v1 artifact
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/754)
> ci: added build and deploy github actions for staging and prod v1

- .size-limit.js
- src/integrations/MicrosoftClarity/browser.js
- src/integrations/MicrosoftClarity/constants.js
- src/integrations/MicrosoftClarity/index.js
- src/integrations/index.js
- src/utils/client_server_name.js
- src/utils/config_to_integration_names.js
- src/utils/integration_cname.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/749)
> feat: onboard microsoft clarity destination

- src/integrations/Braze/browser.js
Its small fix of this PR: https://github.com/rudderlabs/rudder-sdk-js/pull/756
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/761)
> fix: braze update supportDedup

- .size-limit.js
- src/integrations/Axeptio/browser.js
- src/integrations/Axeptio/constants.js
- src/integrations/Axeptio/index.js
- src/integrations/Axeptio/utils.js
- src/integrations/index.js
- src/utils/client_server_name.js
- src/utils/config_to_integration_names.js
- src/utils/integration_cname.js
Onbaord desstination Axeptio
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/752)
> feat: onbaord destination axeptio

- .github/workflows/draft-new-release.yml
Fix issue in the draft new release action
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/764)
> ci: fix name of "master" branch in draft new release github action

- .github/workflows/draft-new-release.yml
- .versionrc
fix the path of root package json in version rc
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/766)
> ci: fix the path of root package json in version rc

- .github/workflows/draft-new-release.yml
- .github/workflows/publish-new-release.yml
- sonar-project.properties
replace pr creation action
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/770)
> ci: replace pr creation action

- .github/workflows/draft-new-release.yml
- .github/workflows/publish-new-release.yml
remove summary from pr creation action
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> ci: remove summary from pr creation action

- .github/workflows/deploy-prod-v1.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-staging-v1.yml
- .github/workflows/deploy-staging.yml
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/780)
> ci: fix git secret key name for bugsnag

- __tests__/utils/errorHandler.test.js
- package-lock.json
- src/core/analytics.js
- src/features/core/session/index.js
- src/utils/beaconQueue.js
- src/utils/errorHandler.js
- src/utils/utils.js
- src/utils/xhrModule.js
Fixed error mutation coming from device mode integrations.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/787)
> fix(core): error mutation coming from integration

- src/core/analytics.js
- src/integrations/GA4/browser.js
- src/integrations/GA4/utils.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/805)
> feat: ga4 hybrid mode support

- __tests__/utils/integrationsData.test.js
- package-lock.json
- package.json
- src/core/analytics.js
- src/utils/IntegrationsData.js
- src/utils/ObjectUtils.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/808)
> feat: ga4 hybrid mode

- README.md
JS SDK snippet in readme updated.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/807)
> chore: js sdk snippet in readme updated

- __tests__/integrations/GA4/utils.test.js
- src/integrations/GA4/utils.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/820)
> fix: detection of sessionId for GA4 if no cookie exists, add unit test

- __tests__/integrations/GA4/utils.test.js
- __tests__/utils/integrationsData.test.js
- src/integrations/GA4/browser.js
- src/integrations/GA4/utils.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat: clientId support in ga4 hybrid mode

- src/integrations/Braze/browser.js
Make logging configurable in braze.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/817)
> feat(braze): make logging configurable

- __tests__/utils/eventProcessorUtils.test.js
- src/core/analytics.js
- src/utils/eventProcessorUtils.js
Fixed context merge bug
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: context merge bug

- CHANGELOG.md
- __tests__/utils/eventProcessorUtils.test.js
- github-release.config.js
- package.json
- packages/npm/package.json
- sonar-project.properties
- src/utils/eventProcessorUtils.js
> chore(release): pulling hotfix-release/2.22.2 into production

- CHANGELOG.md
- __tests__/integrations/FacebookPixel/FacebookPixel.test.js
- package.json
- packages/npm/package.json
- sonar-project.properties
- src/integrations/FacebookPixel/browser.js
> chore(release): pulling hotfix-release/2.22.3 into production

- .github/workflows/build-and-quality-checks-v1.yml
- scripts/integrationBuildScript.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: update v1 github action

- .github/workflows/deploy-sanity-suite.yml
- package.json
- sanity-suite/package-lock.json
- sanity-suite/package.json
- sanity-suite/rollup.config.js
add deploy action for sanity suite, supporl local destination bundles
[Ticket link](https://www.notion.so/rudderstacks/Release-sanity-suite-in-CDN-bd9cbe3d6a7545929047ceb94cd21aae)
- Chrome
>
- Firefox
>
- Safari
>
> ci: add deploy action for sanity suite, supporl local destination bundles

- .github/workflows/deploy-staging-v1.yml
Adding facility to use any feature branch as bugbash branch, and adding condition in github actions to add it to the staging CDN.
To enable the feature branch as a bugbash CDN, we need to create a git tag with `bugbash-<topic>` using command:
`git tag bugbash-<topic>`
`git push --tags`
[Ticket link](https://www.notion.so/rudderstacks/Adding-Action-For-Bugbash-CDN-bee3ddf2cb7a4de0ae05a44b609c4667)
- Chrome
>
- Firefox
>
- Safari
>
> feat(bugbash): adding bugbash tag condition

- __tests__/integrations/GoogleAds/__mocks__/data.js
- __tests__/integrations/GoogleAds/browser.test.js
- __tests__/integrations/GoogleAds/utils.test.js
- src/integrations/GoogleAds/browser.js
- src/integrations/GoogleAds/utils.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat: added support for both click event and dynamic remarketing events

- src/utils/RudderApp.js
- src/utils/RudderMessage.js
Removed redundant properties(action, build) from rudder message.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: remove redundant properties

- packages/npm/index.d.ts
- src/core/analytics.js
Introduced a load option to opt-out from loading the polyfills.
[Ticket link](https://www.notion.so/rudderstacks/Add-an-option-for-the-user-to-opt-out-of-polyfill-loading-955e8b9429084d9c916a2afe5f3fec4e)
- Chrome
>
- Firefox
>
- Safari
>
> feat: option to opt out from loading polyfill

- src/core/analytics.js
- src/utils/utils.js
Fixed the bug that is overriding the SDK library information if provided in options.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: library info override bug

- src/utils/utils.js
Error handling in resolveDataPlaneUrl fn updated
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: updated error handling in resolveDataPlaneUrl

- package-lock.json
- package.json
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: production staging security check issue

- package-lock.json
- package.json
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: pulling latest security fix into hotfix

- package-lock.json
- package.json
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: reverted got package

- src/integrations/GA4/PageEventConfig.js
- src/integrations/GA4/utils.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: added logic to capture full url for ga4 page_location param

- .github/ISSUE_TEMPLATE/bug_report.md
Update the bug report template.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: update issue template for bug report

- src/integrations/GA4/browser.js
- Adding the `send_to` parameter in gtag event call to ensure that event will only be sent to the GA4 property with the measurement id configured in webapp.
- send_to parameter helps in routing data to a patricular GA4 property when more than one instance/properties are loaded.
[Ticket link
](https://www.notion.so/rudderstacks/GA4-Send-send_to-parameter-with-gtag-during-event-calls-d4b077c737004a5f86b1fd22eb756695)
- Chrome
>
- Firefox
>
- Safari
>
> feat(ga4): add sent_to parameter in gtag event call

- .size-limit.js
- __tests__/utils/clientHint.test.js
- packages/npm/index.d.ts
- src/core/analytics.js
- src/utils/clientHint.js
- src/utils/constants.js
Depending on the load option user agent client hint info added in the event context.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat: user agent client hint info added in context

- package-lock.json
- sanity-suite/src/testBook/ignoredProperties.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: sanity suite test cases added

- src/core/analytics.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: update onloaded callback option implementation

- sanity-suite/src/testBook/ignoredProperties.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: sanity suite update

- src/integrations/Braze/browser.js
Added `products` array check
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix(braze): handle undefined products

- src/integrations/GA4/browser.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: ga4 device mode debug_view

- src/integrations/GA4/browser.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: duplicate page views being sent to ga4

- __tests__/utils/integrationsData.test.js
- src/integrations/GA4/browser.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: client_id mapping for ga4

- src/integrations/GA4/browser.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: duplicate userid sent to ga4

- src/integrations/GA4/browser.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: traits are not being sent to ga4 group call

- packages/analytics-js-plugins/src/pocToDelete/RemotePlugin.ts
- packages/analytics-js-plugins/src/pocToDelete/RemotePlugin2.ts
- packages/analytics-js-plugins/src/utilities/globals.ts
- packages/analytics-js/src/components/configManager/types.ts
- packages/analytics-js/src/components/core/Analytics.ts
- packages/analytics-js/src/components/core/IAnalytics.ts
- packages/analytics-js/src/components/core/IRudderStackGlobals.ts
- packages/analytics-js/src/components/core/exposedGlobals.ts
- packages/analytics-js/src/index.ts
- packages/analytics-js/src/state/index.ts
- packages/analytics-js/src/state/indexPOCToDelete.ts
- packages/analytics-js/src/state/slices/context.ts
- packages/analytics-js/src/state/slices/destinations.ts
- packages/analytics-js/src/state/slices/eventBuffer.ts
- packages/analytics-js/src/state/slices/lifecycle.ts
- packages/analytics-js/src/state/slices/metrics.ts
- packages/analytics-js/src/state/slices/nativeDestinations.ts
- packages/analytics-js/src/state/slices/plugins.ts
- packages/analytics-js/src/state/slices/source.ts
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat(analytics-js): add more state slices

- src/integrations/GoogleAds/browser.js
Passing "allow_enhanced_conversions" in config
[Ticket link](https://www.notion.so/rudderstacks/Device-Mode-Google-ads-update-to-support-enhanced-conversions-f3e789538fd344ce95de851544c8b24f)
- Chrome
>
- Firefox
>
- Safari
>
> feat(goole_ads): enhanced conversions

- src/core/analytics.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: event repository initialisation

- src/integrations/GA4/browser.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix(ga4 and ua): cookie conflicts

- src/integrations/GA4/browser.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix(ua and ga4): cookie conflicts

- src/integrations/FacebookPixel/browser.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix(fb_pixel): eslint issue

- .github/workflows/draft-new-release-v1.yml
- CHANGELOG.md
- __tests__/integrations/FacebookPixel/FacebookPixel.test.js
- package-lock.json
- package.json
- src/integrations/BingAds/browser.js
- src/integrations/FacebookPixel/browser.js
- src/integrations/FacebookPixel/utils.js
- src/integrations/GA4/browser.js
- src/integrations/GoogleAds/browser.js
> chore(release): pulling v1-release/1.28.0 into v1-production

- packages/analytics-js/package.json
- packages/analytics-js/rollup-configs/rollup.config.mjs
- packages/analytics-js/src/components/capabilitiesManager/types.ts
- packages/analytics-js/src/components/core/Analytics.ts
- packages/analytics-js/src/components/core/BufferQueue.ts
- packages/analytics-js/src/components/core/IAnalytics.ts
- packages/analytics-js/src/components/core/IRudderAnalytics.ts
- packages/analytics-js/src/components/core/IRudderStackGlobals.ts
- packages/analytics-js/src/components/core/RudderAnalytics.ts
- packages/analytics-js/src/components/core/eventMethodOverloads.ts
- packages/analytics-js/src/components/eventManager/EventManager.ts
- packages/analytics-js/src/components/eventManager/types.ts
- packages/analytics-js/src/components/pluginsManager/types.ts
- packages/analytics-js/src/components/preloadBuffer/index.ts
- packages/analytics-js/src/components/userSessionManager/UserSessionManager.ts
- packages/analytics-js/src/components/utilities/globals.ts
- packages/analytics-js/src/constants/queryParams.ts
- packages/analytics-js/src/index.ts
- packages/analytics-js/src/indexPOCToDelete.ts
- packages/analytics-js/src/services/ErrorHandler/types.ts
- packages/analytics-js/src/services/ExternalSrcLoader/types.ts
- packages/analytics-js/src/services/HttpClient/types.ts
- packages/analytics-js/src/services/Logger/types.ts
- packages/analytics-js/src/services/StoreManager/StoreManager.ts
- packages/analytics-js/src/services/StoreManager/types.ts
- packages/analytics-js/src/state/slices/eventBuffer.ts
- packages/analytics-js/src/state/slices/nativeDestinations.ts
- packages/analytics-js/src/state/types.ts
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> refactor(analytics-js): clean up types & add inline comments as docs

- src/integrations/BingAds/browser.js
Upgrading Bing Ads Track Implementation according to latest Changes at [here](https://help.ads.microsoft.com/#apex/ads/en/56916/2)
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat: bingads Upgraded to latest 

- src/integrations/BingAds/browser.js
Upgrading Bing Ads Track Implementation according to latest Changes at [here](https://help.ads.microsoft.com/#apex/ads/en/56916/2)
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat: bingads Upgraded to latest

- __tests__/integrations/BingAds/BingAds.test.js
- __tests__/integrations/Lemnisk/Lemnisk.test.js
Test Cases Addition for bing ads and a typo for lemnisk test cases
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: added bing ads test cases

- __tests__/integrations/PinterestTag/__mocks__/data.js
- __tests__/integrations/PinterestTag/utils.test.js
- src/integrations/PinterestTag/browser.js
- src/integrations/PinterestTag/utils.js
Send event as `custom` event based on the toggle.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat(pinterest): custom event

- .github/workflows/test.yml
The latest version has issues related to Node version.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: downgrade sonar cloud action version

- CHANGELOG.md
- __tests__/integrations/BingAds/BingAds.test.js
- __tests__/integrations/Lemnisk/Lemnisk.test.js
- __tests__/integrations/PinterestTag/__mocks__/data.js
- __tests__/integrations/PinterestTag/utils.test.js
- package.json
- src/integrations/PinterestTag/browser.js
- src/integrations/PinterestTag/utils.js
> chore(release): pulling v1-release/1.31.0 into v1-production

- .github/workflows/test.yml
- CHANGELOG.md
- __tests__/integrations/BingAds/BingAds.test.js
- __tests__/integrations/Lemnisk/lemnisk.test.js
- __tests__/integrations/PinterestTag/__mocks__/data.js
- __tests__/integrations/PinterestTag/utils.test.js
- package.json
- packages/npm/package.json
- sonar-project.properties
- src/integrations/PinterestTag/browser.js
- src/integrations/PinterestTag/utils.js
> chore(release): pulling release/2.32.0 into production

- src/integrations/GA4/browser.js
- flag based dependency removed for hybrid mode condition check
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix(ga4): updated hybridmode condition check

- .size-limit.js
- src/core/analytics.js
- src/features/core/deviceModeTransformation/transformationHandler.js
Handled undefined destination in transformation response
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: handle undefined destination in transformation response

- __tests__/integrations/Fullstory/fullstory.test.js
- package-lock.json
- package.json
- src/integrations/Fullstory/browser.js
Enhancement in fullstory integration by taking custom fs_host from config
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat: custom host for fullstory

- src/core/analytics.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: updated callback args to use cloned rudderelement

- .size-limit.js
- src/integrations/Amplitude/browser.js
- src/integrations/Amplitude/loader.js
Upgrading the Amplitude SDK version to 8.21.4
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat: upgrade Amplitude SDK version to 8.21.4

- packages/analytics-js/__tests__/components/userSessionManager/userSessionManager.test.ts
- packages/analytics-js/__tests__/components/userSessionManager/utils.test.ts
- packages/analytics-js/__tests__/components/utilities/object.test.ts
- packages/analytics-js/src/components/userSessionManager/UserSessionManager.ts
- packages/analytics-js/src/components/userSessionManager/types.ts
- packages/analytics-js/src/components/userSessionManager/utils.ts
- packages/analytics-js/src/components/utilities/number.ts
- packages/analytics-js/src/components/utilities/object.ts
- packages/analytics-js/src/services/StoreManager/StoreManager.ts
- packages/analytics-js/src/state/types.ts
Session tracking feature in v3
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat: session tracking

- sanity-suite/package-lock.json
- sanity-suite/package.json
- sanity-suite/public/eventFiltering/index-cdn.html
- sanity-suite/public/eventFiltering/index-local.html
- sanity-suite/public/eventFiltering/index-npm.html
- sanity-suite/public/preloadBuffer/index-cdn.html
- sanity-suite/public/preloadBuffer/index-local.html
- sanity-suite/public/preloadBuffer/index-npm.html
- sanity-suite/rollup.config.js
- sanity-suite/src/index-npm.js
Add ability to generate different sanity pages for feature specific configurations
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> test: add feature pages in sanity suite build configs

- package-lock.json
- patches/@segment+localstorage-retry+1.3.0.patch
- src/utils/beaconQueue.js
Attempt to fix minor issue and add more info to issues flagged by bugsnag 
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: localstorage db connections buzy issue in outdated browsers

- src/integrations/GA4/browser.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix(ga4): reverted cookie prefix change

- src/integrations/SnapPixel/util.js
snap pixel mapping of price and number_item fields
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: snap pixel mapping

- src/integrations/SnapPixel/util.js
snap pixel price and number_items mapping
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: snap pixel price mapping

- .github/workflows/build-and-quality-checks-v3.yml
- .github/workflows/test-v3.yml
- package.json
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: fix size check issues

- packages/analytics-js-plugins/__tests__/consentManager/index.test.ts
- packages/analytics-js-plugins/__tests__/oneTrust/index.test.ts
- packages/analytics-js-plugins/src/consentManager/index.ts
- packages/analytics-js-plugins/src/index.ts
- packages/analytics-js-plugins/src/oneTrust/index.ts
- packages/analytics-js-plugins/src/oneTrust/types.ts
- packages/analytics-js-plugins/src/types/common.ts
- packages/analytics-js/__tests__/components/utilities/consent.test.ts
- packages/analytics-js/src/components/configManager/ConfigManager.ts
- packages/analytics-js/src/components/configManager/types.ts
- packages/analytics-js/src/components/core/Analytics.ts
- packages/analytics-js/src/components/pluginsManager/PluginsManager.ts
- packages/analytics-js/src/components/pluginsManager/defaultPluginsList.ts
- packages/analytics-js/src/components/pluginsManager/legacyBuildPluginImports.ts
- packages/analytics-js/src/components/pluginsManager/modernBuildPluginImports.ts
- packages/analytics-js/src/components/pluginsManager/pluginNames.ts
- packages/analytics-js/src/components/pluginsManager/types.ts
- packages/analytics-js/src/components/utilities/consent.ts
- packages/analytics-js/src/state/slices/consents.ts
- packages/analytics-js/src/state/types.ts
- packages/analytics-js/src/types/remote-plugins.d.ts
* feat: consent manager plugin
* chore: code refactoring
* test: consent manager test cases
* chore: code refactoring
* chore: extension point added to check destination is consented, code refactoring
* chore: code refactoring
* chore: code refactoring
* chore: comments addressed
* chore: comments addressed
* chore: test case added
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat: consent manager plugin (#1096)

- packages/analytics-js-plugins/__tests__/consentManager/index.test.ts
- packages/analytics-js-plugins/src/consentManager/index.ts
- packages/analytics-js-plugins/src/consentManager/type.ts
- packages/analytics-js/src/components/core/Analytics.ts
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: pass batch as argument in plugin extension point

- packages/analytics-js-plugins/rollup.config.mjs
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix(monorepo): expose one trust plugin in remores app

- packages/sanity-suite/public/v3/index-cdn.html
- packages/sanity-suite/public/v3/index-local.html
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore:  v3 Test Added Preload buffer call

- src/core/analytics.js
- src/utils/utils.js
Removed vulnerable package component-URL, instead used URL() constructor to extract the query param.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: removed vulnerable package component-url

- packages/analytics-js/src/state/slices/loadOptions.ts
- packages/analytics-js/src/state/types.ts
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: auto detection of destSDKBaseUrl

- packages/analytics-js/src/state/slices/loadOptions.ts
- packages/analytics-js/src/state/types.ts
- packages/analytics-v1.1/src/integrations/RedditPixel/constants.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: merge latest from v3-staging

- packages/analytics-js/src/components/userSessionManager/UserSessionManager.ts
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: auto capture anonymous id

- packages/analytics-js-plugins/__tests__/nativeDestinationQueue/utilities.test.ts
- packages/analytics-js-plugins/src/nativeDestinationQueue/index.ts
- packages/analytics-js-plugins/src/nativeDestinationQueue/utilities.ts
- packages/analytics-js/src/components/userSessionManager/UserSessionManager.ts
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: merge latest changes from v3 staging

- packages/analytics-js/__tests__/components/configManager/dataPlaneResolver.test.ts
- packages/analytics-js/__tests__/components/core/Analytics.test.ts
- packages/analytics-js/src/components/configManager/ConfigManager.ts
- packages/analytics-js/src/components/configManager/util/dataPlaneResolver.ts
- packages/analytics-js/src/components/core/Analytics.ts
- Made data plane Url optional in load call.
- Update unit test cases
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: data residency

- src/integrations/GA4/browser.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix(ga4): use function to fetch user traits

- CHANGELOG.md
- package.json
- packages/npm/package.json
- sonar-project.properties
- src/core/analytics.js
> chore(release): pulling hotfix-release/2.35.1 into production

- .github/workflows/build-and-quality-checks.yml
- package-lock.json
- packages/analytics-v1.1/.size-limit.js
- packages/analytics-v1.1/CHANGELOG.md
- packages/analytics-v1.1/package.json
- packages/analytics-v1.1/src/core/analytics.js
- packages/analytics-v1.1/src/integrations/GA4/browser.js
- packages/analytics-v1.1/src/utils/storage/storage.js
- packages/sanity-suite/__fixtures__/identify8.json
- packages/sanity-suite/package.json
- packages/sanity-suite/src/testBookSuites/identify.js
pulled in latest release changes
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: sync latest from v1.1

- public/index.html
- src/utils/beaconQueue.js
attach beacon flush on visibility change event hidden value to tackle issue https://github.com/rudderlabs/rudder-sdk-js/issues/1175
[Ticket link](https://www.notion.so/rudderstacks/Update-v1-1-beacon-to-use-visibility-API-7d7c542b97294ff392088d65bffdf3fe?pvs=4)
- Chrome
>
- Firefox
>
- Safari
>
> feat: attach beacon flush on visibility change event hidden value

- .github/workflows/deploy-beta.yml
- .size-limit.js
- package-lock.json
- package.json
Update CryptoJs to latest version
[Ticket link](https://www.notion.so/rudderstacks/Github-PR-to-update-cryptojs-package-572ba724823246fe894b0c97ae6e0ef3?pvs=4)
- Chrome
>
- Firefox
>
- Safari
>
> fix: update crypto-js to latest version to ensure crypto random values

- packages/analytics-js-plugins/src/deviceModeDestinations/index.ts
- patches/@segment+localstorage-retry+1.3.0.patch
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: sync v3-staging to beta/3.0.0-beta

- packages/analytics-js-plugins/src/deviceModeDestinations/index.ts
- patches/@segment+localstorage-retry+1.3.0.patch
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: sync v3-staging to beta/v3

- packages/analytics-js-common/src/types/Store.ts
- packages/analytics-js/src/services/StoreManager/component-cookie/index.ts
I have added the missing `samesite` configuration option for cookies.
Also, removed unwanted error handling.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: cookie storage options

- CHANGELOG.md
- package.json
- packages/npm/package.json
- sonar-project.properties
- src/integrations/Mixpanel/browser.js
> chore(release): pulling hotfix-release/2.37.1 into production

- packages/analytics-js-common/src/services/ExternalSrcLoader/ExternalSrcLoader.ts
- packages/analytics-js-common/src/types/HttpClient.ts
- packages/analytics-js-common/src/types/Store.ts
- packages/analytics-js/__tests__/components/core/Analytics.test.ts
- packages/analytics-js/__tests__/services/ErrorHandler/processError.test.ts
- packages/analytics-js/src/components/configManager/ConfigManager.ts
- packages/analytics-js/src/components/core/Analytics.ts
- packages/analytics-js/src/components/core/IAnalytics.ts
- packages/analytics-js/src/components/userSessionManager/UserSessionManager.ts
- packages/analytics-js/src/components/userSessionManager/types.ts
- packages/analytics-js/src/components/utilities/loadOptions.ts
- packages/analytics-js/src/constants/logMessages.ts
- packages/analytics-js/src/services/ErrorHandler/processError.ts
- packages/analytics-js/src/services/HttpClient/HttpClient.ts
- packages/analytics-js/src/services/StoreManager/Store.ts
- packages/analytics-js/src/services/StoreManager/StoreManager.ts
- packages/analytics-js/src/services/StoreManager/storages/InMemoryStorage.ts
- packages/analytics-js/src/services/StoreManager/storages/LocalStorage.ts
- packages/analytics-js/src/services/StoreManager/storages/defaultOptions.ts
- Removed Global error handler attachment as it's not needed anymore.
- Refactored the storage engines
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat: storage service improvements

- CHANGELOG.md
- package.json
- packages/npm/package.json
- sonar-project.properties
- src/integrations/Mixpanel/browser.js
> chore(release): pulling hotfix-release/2.38.1 into production

- src/core/analytics.js
- src/features/core/session/index.js
- src/utils/storage/cookie.js
- src/utils/storage/memoryStorage.js
- src/utils/storage/storage.js
- src/utils/storage/store.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat: persistent storage flexibility

- packages/sanity-suite/rollup.config.mjs
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> test(monorepo): fix sanity suite build config

- sanity-suite/src/testBook/ResultAssertions.js
Fix sanity suite test case for source config
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: fix sanity suite test case for sourceConfig

- src/integrations/Engage/browser.js
Minor Logger fix for engage page call
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: typo for engage page call

- .size-limit.js
- CHANGELOG.md
- assets/adobe-analytics-js/adobe-analytics-heartbeat.js
- assets/adobe-analytics-js/adobe-analytics-js.js
- package.json
- packages/npm/package.json
- sonar-project.properties
- src/integrations/CustomerIO/browser.js
- src/integrations/Engage/browser.js
- src/integrations/Mixpanel/browser.js
> chore(release): pulling release/2.40.0 into production

- packages/analytics-js-common/src/utilities/object.ts
- packages/analytics-js/public/index.html
- packages/analytics-js/src/components/utilities/loadOptions.ts
Resolved incompatibility issues with loading the SDK in IE11.
[Ticket link](https://linear.app/rudderstack/issue/SDK-150/dev-testing-for-v3-after-refactoring)
- Chrome
>
- Firefox
>
- Safari
>
> fix: ie11 incompatibility issues

- packages/sanity-suite/__fixtures__/eventFiltering1.json
- packages/sanity-suite/__fixtures__/eventFiltering2.json
- packages/sanity-suite/public/v3/eventFiltering/index-cdn.html
- packages/sanity-suite/public/v3/preloadBuffer/index-cdn.html
- packages/sanity-suite/src/testBookSuites/eventFiltering.js
- packages/sanity-suite/src/testBookSuites/index.js
1. Add TC for eventFiltering
2. Add GA supported JSON 
3. Add Blaze, Amplitude  supported JSON 
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: event filtering feature test case added 

- .github/workflows/deploy-beta-v3.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-prod-v3.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-staging.yml
- .github/workflows/rollback-v3.yml
- .github/workflows/rollback.yml
- packages/analytics-js/__tests__/components/core/Analytics.test.ts
- packages/analytics-js/public/index.html
- packages/analytics-js/src/components/core/Analytics.ts
- packages/analytics-js/src/components/core/IAnalytics.ts
add RSA_Initialiser & RSA_Ready event dispatching
[Ticket link](https://linear.app/rudderstack/issue/SDK-167/publish-events-on-load-and-on-ready-to-window)
- Chrome
>
- Firefox
>
- Safari
>
> feat(analytics-js): add RSA_Initialiser & RSA_Ready event dispatching

- .github/workflows/build-and-quality-checks-v3.yml
- .github/workflows/create-hotfix-branch-v3.yml
- .github/workflows/deploy-beta-v3.yml
- .github/workflows/deploy-dev-v3.yml
- .github/workflows/deploy-npm-v3.yml
- .github/workflows/deploy-prod-v3.yml
- .github/workflows/deploy-staging-v3.yml
- .github/workflows/draft-new-release-v3.yml
- .github/workflows/publish-new-release-v3.yml
- .github/workflows/rollback-v3.yml
- .github/workflows/test-v3.yml
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> ci: update v3 github actions

- README.md
- package.json
- packages/analytics-js-common/README.md
- packages/analytics-js-common/package.json
- packages/analytics-js-integrations/README.md
- packages/analytics-js-integrations/package.json
- packages/analytics-js-plugins/README.md
- packages/analytics-js-plugins/package.json
- packages/analytics-js-service-worker/README.md
- packages/analytics-js-service-worker/package.json
- packages/analytics-js/README.md
- packages/analytics-js/package.json
- packages/analytics-v1.1/README.md
- packages/analytics-v1.1/package.json
- packages/loading-scripts/README.md
- packages/loading-scripts/package.json
- packages/sanity-suite/README.md
- packages/sanity-suite/package.json
update all README files for the packages
[Ticket link](https://linear.app/rudderstack/issue/SDK-274/update-readme-files-in-all-packages)
- Chrome
>
- Firefox
>
- Safari
>
> docs(monorepo): update all README files

- packages/analytics-js-plugins/__tests__/ketchConsentManager/index.test.ts
- packages/analytics-js-plugins/__tests__/oneTrustConsentManager/index.test.ts
- packages/analytics-js-plugins/__tests__/storageMigrator/index.test.ts
- packages/analytics-js-plugins/src/beaconQueue/index.ts
- packages/analytics-js-plugins/src/deviceModeDestinations/index.ts
- packages/analytics-js-plugins/src/deviceModeDestinations/utils.ts
- packages/analytics-js-plugins/src/ketchConsentManager/index.ts
- packages/analytics-js-plugins/src/nativeDestinationQueue/utilities.ts
- packages/analytics-js-plugins/src/oneTrustConsentManager/index.ts
- packages/analytics-js-plugins/src/storageMigrator/constants.ts
- packages/analytics-js-plugins/src/storageMigrator/index.ts
- packages/analytics-js-plugins/src/utilities/logMessages.ts
- packages/analytics-js/__tests__/components/userSessionManager/userSessionManager.test.ts
- packages/analytics-js/__tests__/services/ErrorHandler/ErrorHandler.test.ts
- packages/analytics-js/rollup.config.mjs
- packages/analytics-js/src/components/capabilitiesManager/CapabilitiesManager.ts
- packages/analytics-js/src/components/configManager/ConfigManager.ts
- packages/analytics-js/src/components/core/Analytics.ts
- packages/analytics-js/src/components/eventRepository/EventRepository.ts
- packages/analytics-js/src/components/userSessionManager/UserSessionManager.ts
- packages/analytics-js/src/components/utilities/loadOptions.ts
- packages/analytics-js/src/constants/logMessages.ts
- packages/analytics-js/src/services/ErrorHandler/ErrorHandler.ts
- packages/analytics-js/src/services/StoreManager/Store.ts
- packages/analytics-v1.1/rollup-configs/rollup.utilities.mjs
- packages/loading-scripts/rollup.config.mjs
- packages/sanity-suite/rollup.config.mjs
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix: error reporting

- packages/analytics-js-plugins/src/utilities/queue.ts
https://linear.app/rudderstack/issue/SDK-150/dev-testing-for-v3-after-refactoring
- Chrome
>
- Firefox
>
- Safari
>
> fix: integrations data override to match with v1.1

- src/utils/utils.js
https://linear.app/rudderstack/issue/SDK-318/fix-integrations-data-values-resolution
- Chrome
>
- Firefox
>
- Safari
>
> fix: integration data values resolution

- .size-limit.js
- CHANGELOG.md
- package.json
- packages/npm/package.json
- sonar-project.properties
- src/core/analytics.js
- src/utils/errorHandler.js
- src/utils/utils.js
> chore(release): pulling hotfix-release/2.40.1 into production

- .size-limit.js
- CHANGELOG.md
- jest/jest.polyfills.js
- package.json
- packages/npm/package.json
- sonar-project.properties
- src/core/analytics.js
- src/utils/constants.js
- src/utils/storage/storage.js
- src/utils/storage/v3DecryptionUtils.js
> chore(release): pulling hotfix-release/2.40.2 into production

- .github/workflows/build-and-quality-checks-v3.yml
- .github/workflows/build-and-quality-checks.yml
- .github/workflows/check_pr_title.yml
- .github/workflows/test-v3.yml
- .github/workflows/test.yml
GitHub workflows like tests, title check, and build are now enabled for hotfix PRs too.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> chore: enable workflows for hotfix prs

- package.json
https://linear.app/rudderstack/issue/SDK-344/use-correct-flag-for-skipping-tags-during-releases
- Chrome
>
- Firefox
>
- Safari
>
> chore: skip tags for lerna versioned releases

- package.json
https://linear.app/rudderstack/issue/SDK-344/use-correct-flag-for-skipping-tags-during-releases
- Chrome
>
- Firefox
>
- Safari
>
> chore: cleanup lerna version script

- .github/workflows/deploy-prod.yml
- CHANGELOG.md
- package.json
- packages/npm/package.json
- sonar-project.properties
> chore(release): pulling hotfix-release/2.40.4 into production

- .github/workflows/check_pr_title.yml
- .github/workflows/deploy-beta-v3.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-dev-v3.yml
- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-npm-v3.yml
- .github/workflows/deploy-npm.yml
- .github/workflows/deploy-prod-v3.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-sanity-suite.yml
- .github/workflows/deploy-staging-v3.yml
- .github/workflows/deploy-staging.yml
- .github/workflows/draft-new-release.yml
- .github/workflows/publish-new-release-v3.yml
- .github/workflows/rollback-v3.yml
https://linear.app/rudderstack/issue/SDK-356/cleanup-github-workflows
- Chrome
>
- Firefox
>
- Safari
>
> chore: cleanup and fix issues in workflows

- src/integrations/Klaviyo/browser.js
Reverts rudderlabs/rudder-sdk-js#1338
> Revert "fix: add trim & lowercase for klaviyo track event"

- CHANGELOG.md
- __tests__/integrations/Mixpanel/browser.test.js
- package.json
- packages/npm/package.json
- sanity-suite/package-lock.json
- sanity-suite/package.json
- sonar-project.properties
- src/integrations/Klaviyo/browser.js
- src/integrations/Mixpanel/browser.js
- src/utils/beaconQueue.js
> chore(release): pulling hotfix-release/2.40.5 into production

- packages/analytics-js/rollup.config.mjs
- packages/analytics-js/src/components/capabilitiesManager/CapabilitiesManager.ts
- packages/analytics-js/src/components/configManager/ConfigManager.ts
- packages/analytics-js/src/components/utilities/loadOptions.ts
- packages/analytics-js/src/constants/logMessages.ts
- packages/analytics-v1.1/rollup-configs/rollup.utilities.mjs
- packages/loading-scripts/rollup.config.mjs
- packages/sanity-suite/rollup.config.mjs
- Added a callback function to the default polyfill URL to determine the success of polyfill load.
https://linear.app/rudderstack/issue/SDK-365/js-sdk-v3-check-if-polyfills-are-evaluated-properly-with-a-callback
- Chrome
>
- Firefox
>
- Safari
>
> feat: add callback for polyfill load

- src/integrations/Heap/nativeSdkLoader.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> fix(heap): heap.push is not a function

- src/integrations/ActiveCampaign/browser.js
pass email in page call fro active campaign
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat: pass email in page call

- package.json
- packages/analytics-js-common/project.json
- packages/analytics-js-integrations/project.json
- packages/analytics-js-plugins/project.json
- packages/analytics-js-service-worker/project.json
- packages/analytics-js/project.json
- packages/analytics-v1.1/CHANGELOG_LATEST.md
- packages/analytics-v1.1/project.json
- packages/loading-scripts/project.json
- packages/sanity-suite/project.json
- scripts/generate-last-release-changelog.sh
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> ci(monorepo): fix issue with version tags and beta

- .size-limit.js
- src/integrations/Appcues/browser.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
> feat(INT-645): added proxyUrl support

- .github/workflows/draft-new-release-v3.yml
> ci: use setup ci command

- .github/workflows/draft-new-release-v3.yml
- packages/sanity-suite/rollup.config.mjs
> ci: revert setup ci command

- package-lock.json
- package.json
- packages/analytics-js-integrations/CHANGELOG.md
- packages/analytics-js-integrations/CHANGELOG_LATEST.md
- packages/analytics-js-integrations/package.json
- packages/analytics-js-integrations/project.json
- packages/analytics-js-integrations/src/integrations/TVSquared/browser.js
- packages/analytics-js-integrations/src/integrations/TVSquared/utils.js
- sonar-project.properties
> chore(release): pulling v3-hotfix-release/3.0.0-beta.10 into main

- packages/analytics-js-plugins/__tests__/utilities/retryQueue/RetryQueue.test.ts
- packages/analytics-js-plugins/src/utilities/retryQueue/RetryQueue.ts
> feat: simplify queue batching options

- .prettierignore
- packages/analytics-js/public/index.html
- packages/analytics-js/src/components/capabilitiesManager/detection/dom.ts
- patches/crypto-es+2.0.4.patch
[Linear task link](https://linear.app/rudderstack/issue/SDK-646/fix-ie11-compatibility-for-crypto-es)
> fix(analytics-js-plugins): add IE11 compatibility for crypto-es

- .prettierignore
- package-lock.json
- package.json
- packages/analytics-js/CHANGELOG.md
- packages/analytics-js/CHANGELOG_LATEST.md
- packages/analytics-js/package.json
- packages/analytics-js/project.json
- packages/analytics-js/public/index.html
- packages/analytics-js/src/components/capabilitiesManager/detection/dom.ts
- packages/sanity-suite/CHANGELOG.md
- packages/sanity-suite/package.json
- patches/crypto-es+2.0.4.patch
- sonar-project.properties
> chore(release): pulling v3-release/3.0.0-beta.13 into main

- packages/analytics-js/src/components/utilities/page.ts
- packages/analytics-v1.1/src/utils/pageProperties.js
> fix(analytics-js,rudder-sdk-js): dead object issue

- packages/analytics-js-integrations/src/integrations/Amplitude/browser.js
- packages/analytics-js-integrations/src/integrations/Amplitude/nativeSdkLoader.js
> feat(Amplitude): update amplitude SDK 

- packages/sanity-suite/__fixtures__/sourceConfig1.json
> chore: source config sanity test case fix

- packages/analytics-js-integrations/__tests__/integrations/GA4/__mocks__/data.js
- packages/analytics-js-integrations/__tests__/integrations/GA4/browser.test.js
- packages/analytics-js-integrations/__tests__/integrations/GA4/utils.test.js
- packages/analytics-js-integrations/src/integrations/GA4/browser.js
- packages/analytics-js-integrations/src/integrations/GA4/utils.js
> feat(analytics-js-integrations): ga4 enhancements

- packages/analytics-js-integrations/__tests__/integrations/GA4/browser.test.js
- packages/analytics-js-integrations/__tests__/integrations/GA4/utils.test.js
- packages/analytics-js-integrations/src/integrations/GA4/browser.js
- packages/analytics-js-integrations/src/integrations/GA4/utils.js
> fix(ga4): remove sendUserTraitsAsPartOfInIt field

- packages/analytics-js-integrations/__tests__/integrations/GA4/utils.test.js
- packages/analytics-js-integrations/src/integrations/GA4/browser.js
- packages/analytics-js-integrations/src/integrations/GA4/utils.js
> fix(ga4): override pii property values to null

- package-lock.json
- package.json
- packages/analytics-js-integrations/CHANGELOG.md
- packages/analytics-js-integrations/CHANGELOG_LATEST.md
- packages/analytics-js-integrations/__tests__/integrations/GA4/__mocks__/data.js
- packages/analytics-js-integrations/__tests__/integrations/GA4/browser.test.js
- packages/analytics-js-integrations/__tests__/integrations/GA4/utils.test.js
- packages/analytics-js-integrations/package.json
- packages/analytics-js-integrations/project.json
- packages/analytics-js-integrations/src/integrations/GA4/browser.js
- packages/analytics-js-integrations/src/integrations/GA4/utils.js
- sonar-project.properties
> chore(release): pulling v3-hotfix-release/3.0.0-beta.14 into main

- .github/workflows/deploy-npm-v3.yml
- .github/workflows/publish-new-release-v3.yml
- examples/serverless/vercel-edge/package-lock.json
- examples/serverless/vercel-edge/package.json
- package-lock.json
- package.json
- packages/analytics-js-integrations/CHANGELOG.md
- packages/analytics-js-integrations/CHANGELOG_LATEST.md
- packages/analytics-js-integrations/package.json
- packages/analytics-js-integrations/project.json
- packages/analytics-js-integrations/src/integrations/Amplitude/browser.js
- packages/analytics-js-integrations/src/integrations/Amplitude/nativeSdkLoader.js
- packages/analytics-js/CHANGELOG.md
- packages/analytics-js/CHANGELOG_LATEST.md
- packages/analytics-js/package.json
- packages/analytics-js/project.json
- packages/analytics-js/src/components/utilities/page.ts
- packages/analytics-v1.1/CHANGELOG.md
- packages/analytics-v1.1/CHANGELOG_LATEST.md
- packages/analytics-v1.1/package.json
- packages/analytics-v1.1/project.json
- packages/analytics-v1.1/src/utils/pageProperties.js
- packages/sanity-suite/CHANGELOG.md
- packages/sanity-suite/__fixtures__/sourceConfig1.json
- packages/sanity-suite/package.json
- packages/sanity-suite/src/index-npm.ts
- sonar-project.properties
> chore(release): pulling v3-release/3.0.0-beta.15 into main

- packages/analytics-js-plugins/src/xhrQueue/types.ts
- packages/analytics-js-plugins/src/xhrQueue/utilities.ts
- packages/analytics-js/src/components/configManager/types.ts
> chore: update source config response type

- packages/analytics-js/src/components/userSessionManager/UserSessionManager.ts
> fix: pass anonymous id load option to getanonymousid method

- .github/workflows/test-v3.yml
> ci(monorepo): add codecov action

- packages/analytics-js-integrations/src/integrations/TVSquared/browser.js
Reverts rudderlabs/rudder-sdk-js#1430
> Revert "chore: remove duplicate config named eventWhiteList"

- packages/sanity-suite/public/v3/index-cdn.html
- packages/sanity-suite/public/v3/index-local.html
1. Removed  Preload Buffer calls to  segment AnonymousId TC
2. Added Config for Segment  AnonymousId TC
> feat: remove preload buffer for segment AnonymousId TC

- .github/workflows/build-and-quality-checks-v3.yml
- package-lock.json
- packages/analytics-js-common/types/rudderanalytics.d.ts
- packages/analytics-js/src/components/preloadBuffer/types.ts
- packages/analytics-js/src/index.ts
- packages/analytics-js/src/types/rudderanalytics.d.ts
- packages/loading-scripts/package.json
- packages/loading-scripts/project.json
- packages/loading-scripts/src/index.ts
- packages/loading-scripts/src/types/rudderanalytics.d.ts
- packages/sanity-suite/src/types/rudderanalytics.d.ts
Minor update on global declare type and fixed loading snippet type issues
[Linear task link](https://linear.app/rudderstack/issue/SDK-784/fix-loading-snippet-type-build-issues)
> fix(analytics-js): correct declared global extended type

- .github/workflows/build-and-quality-checks-v3.yml
- package.json
> chore: build packages upon install

- packages/analytics-js-integrations/__tests__/integrations/Braze/Braze.test.js
unit tests for braze integration
> test(analytics-js-integrations): unit tests for braze integration

- packages/analytics-js-integrations/__tests__/integrations/Intercom/browser.test.js
- packages/analytics-js-integrations/__tests__/integrations/Intercom/util.test.js
Resolves INT-790
- This PR adds tests for Intercom destination
> chore: add tests for intercom destination

- packages/analytics-js-integrations/__tests__/integrations/Hotjar/browser.test.js
- packages/analytics-js-integrations/__tests__/integrations/Intercom/browser.test.js
Add tests for hotjar destination
Resolves INT-893
> chore: add tests for hotjar destination

- packages/analytics-js-integrations/__tests__/integrations/Braze/Braze.test.js
- packages/analytics-js-integrations/src/integrations/Braze/browser.js
- packages/analytics-js-integrations/src/integrations/Braze/nativeSdkLoader.js
Resolves INT-503
(INT-503) hybrid mode braze support
> feat: hybrid mode braze

- packages/analytics-js-plugins/__tests__/deviceModeDestinations/utils.test.ts
- packages/analytics-js-plugins/__tests__/utilities/destination.test.ts
- packages/analytics-js-plugins/src/deviceModeDestinations/index.ts
- packages/analytics-js-plugins/src/deviceModeDestinations/utils.ts
- packages/analytics-js-plugins/src/utilities/destination.ts
- packages/analytics-js/__tests__/components/core/Analytics.test.ts
- packages/analytics-js/__tests__/components/utilities/consent.test.ts
- packages/analytics-js/src/components/eventManager/utilities.ts
- packages/analytics-js/src/components/utilities/consent.ts
https://linear.app/rudderstack/issue/SDK-815/manual-testing-and-test-book-for-gcm-phase-i
> fix: gcm post consent issues

- packages/analytics-js-common/.size-limit.js
- patches/@segment+localstorage-retry+1.3.0.patch
> fix: cloud mode event delivery for event with circular dependency

- packages/analytics-js-plugins/__tests__/xhrQueue/index.test.ts
- packages/analytics-js-plugins/__tests__/xhrQueue/utilities.test.ts
- packages/analytics-js-plugins/src/beaconQueue/index.ts
- packages/analytics-js-plugins/src/beaconQueue/types.ts
- packages/analytics-js-plugins/src/beaconQueue/utilities.ts
- packages/analytics-js-plugins/src/utilities/eventsDelivery.ts
- packages/analytics-js-plugins/src/xhrQueue/index.ts
- packages/analytics-js-plugins/src/xhrQueue/types.ts
- packages/analytics-js-plugins/src/xhrQueue/utilities.ts
- packages/analytics-v1.1/src/utils/beaconQueue.js
> feat: introduced root level sentat for batch request

- packages/analytics-v1.1/__tests__/ketchConsent.test.js
- packages/analytics-v1.1/__tests__/oneTrustCookieConsent.test.js
- packages/analytics-v1.1/src/core/analytics.js
- packages/analytics-v1.1/src/features/core/cookieConsent/OneTrust/browser.js
- packages/analytics-v1.1/src/features/core/cookieConsent/ketch/browser.js
- packages/sanity-suite/rollup.config.mjs
- packages/sanity-suite/src/ignoredProperties/ignoredProperties.js
Reverts rudderlabs/rudder-sdk-js#1534
> chore: revert "feat(analytics-js): add additional consent management fields"

- packages/analytics-js-integrations/src/integrations/BingAds/browser.js
- packages/analytics-js-integrations/src/integrations/Mixpanel/util.js
> fix(bing_ads): name and display name import

- package-lock.json
- package.json
- packages/analytics-js-integrations/CHANGELOG.md
- packages/analytics-js-integrations/CHANGELOG_LATEST.md
- packages/analytics-js-integrations/package.json
- packages/analytics-js-integrations/project.json
- packages/analytics-js-integrations/src/integrations/BingAds/browser.js
- packages/analytics-js-integrations/src/integrations/Mixpanel/util.js
- sonar-project.properties
> chore(release): pulling v3-hotfix-release/3.0.0-beta.22 into main

- package-lock.json
- package.json
- packages/analytics-js-integrations/CHANGELOG.md
- packages/analytics-js-integrations/CHANGELOG_LATEST.md
- packages/analytics-js-integrations/package.json
- packages/analytics-js-integrations/project.json
- packages/analytics-js-integrations/src/integrations/BingAds/browser.js
- packages/analytics-js-integrations/src/integrations/Mixpanel/util.js
- sonar-project.properties
> chore(release): pulling main into develop post release v3.0.0-beta.22

- packages/analytics-v1.1/src/core/analytics.js
- packages/analytics-v1.1/src/features/core/metrics/errorReporting/ErrorReportingService.js
- packages/analytics-v1.1/src/features/core/metrics/errorReporting/providers/Bugsnag.js
> feat: use writekey as user in bugsnag

- packages/analytics-js-integrations/__tests__/integrations/Clevertap/browser.test.js
- packages/analytics-js-integrations/src/integrations/Clevertap/browser.js
> fix(clevertap): region undefined issue

- packages/analytics-js-plugins/src/nativeDestinationQueue/index.ts
- packages/analytics-js/src/components/eventRepository/EventRepository.ts
- packages/analytics-js/src/constants/logMessages.ts
- packages/analytics-v1.1/src/core/analytics.js
> fix: enhance error handling

- package-lock.json
- package.json
- packages/analytics-js-common/package.json
- packages/analytics-js-plugins/package.json
- packages/analytics-js-service-worker/package.json
- packages/analytics-js-service-worker/src/Analytics.ts
- packages/analytics-js/package.json
- patches/@segment+localstorage-retry+1.3.0.patch
> fix: localstorage retry patch and upgrade packages

- packages/sanity-suite/__fixtures__/sourceConfig1.json
- packages/sanity-suite/__fixtures__/sourceConfigDMT1.json
- packages/sanity-suite/__fixtures__/sourceConfigDev1.json
Update the sanity suite sourceConfig API test case fixtures to reflect to expected changes for supportedMessageTypes property
[Linear task link](https://linear.app/rudderstack/issue/SDK-1121/update-sanity-suite-fixtures)
> fix(analytics-js-sanity-suite): update sourceConfig fixtures

- packages/analytics-js-integrations/__tests__/common/common.test.js
> chore: added test to validate integration export and init, isLoaded and isReady method

- package-lock.json
- package.json
- packages/analytics-js-integrations/CHANGELOG.md
- packages/analytics-js-integrations/CHANGELOG_LATEST.md
- packages/analytics-js-integrations/package.json
- packages/analytics-js-integrations/project.json
- packages/analytics-js-integrations/src/integrations/RedditPixel/browser.js
- packages/analytics-js-integrations/src/integrations/RedditPixel/nativeSdkLoader.js
- sonar-project.properties
> chore(release): pulling v3-hotfix-release/3.0.0-beta.26 into main

- package-lock.json
- package.json
- packages/analytics-js-integrations/.size-limit.js
- packages/analytics-js-integrations/__tests__/utils/commonUtils.test.js
- packages/analytics-js-integrations/package.json
- packages/analytics-js-integrations/src/utils/commonUtils.js
- packages/analytics-js-plugins/__tests__/bugsnag/utils.test.ts
Replaces `lodash.pick` with `pick` from `ramda`.
Before:
```
➜  rudder-sdk-js git:(develop) npm run check:security
> @rudderstack/analytics-js-monorepo@3.0.0-beta.26 check:security
> npm audit --recursive --audit-level=high
ip  *
Severity: high
NPM IP package vulnerable to Server-Side Request Forgery (SSRF) attacks - https://github.com/advisories/GHSA-78xj-cgh5-2h22
fix available via `npm audit fix`
node_modules/ip
socks  1.0.0 - 2.7.1
Depends on vulnerable versions of ip
node_modules/socks
lodash.pick  >=4.0.0
Severity: high
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
fix available via `npm audit fix --force`
Will install lodash.pick@3.1.0, which is a breaking change
node_modules/lodash.pick
3 high severity vulnerabilities
To address issues that do …
```
> fix: replace lodash.pick with ramda to avoid vulnerabilities

- packages/sanity-suite/__fixtures__/sourceConfig1.json
Update sanity suite expected payloads after destination config changes
> test(analytics-js-sanity-suite): update expected sourceConfig response

- .github/workflows/build-and-quality-checks-v3.yml
- package-lock.json
- package.json
Upgrade vulnerable package "ip"
[Linear task link](https://linear.app/rudderstack/issue/SDK-1338/fix-npm-package-vulnerabilities-in-js-sdk)
> fix(analytics-js): upgrade vulnerable dependency "ip" to secure version

- package-lock.json
- package.json
- packages/analytics-js-service-worker/package.json
- packages/analytics-v1.1/package.json
update component-type to latest for TS
[Linear task link](https://linear.app/rudderstack/issue/SDK-948/update-component-type-dependency)
> fix(analytics-js-service-worker): update component-type to latest for TS

- packages/analytics-js/__tests__/components/eventManager/utilities.test.ts
- packages/analytics-js/src/components/eventManager/constants.ts
Reserve element/properties list in JS SDK has been updated
SDK-529
> feat: reserved elements list updated

- packages/analytics-js-integrations/__tests__/integrations/Reddit_pixel/utils.test.js
- packages/analytics-js-integrations/src/integrations/RedditPixel/browser.js
- packages/analytics-js-integrations/src/integrations/RedditPixel/utils.js
We are adding hashing of user traits through this pr
> fix: add hashing to user traits of reddit_pixel  

- packages/analytics-js-integrations/__tests__/integrations/Posthog/browser.test.js
> test: add test cases for posthog profiles

- packages/analytics-js-integrations/__tests__/integrations/SnapPixel/browser.test.js
- packages/analytics-js-integrations/src/integrations/SnapPixel/browser.js
> fix: age format snapPixel

- packages/analytics-js-integrations/__tests__/integrations/MoEngage/browser.test.ts
- packages/analytics-js-integrations/src/integrations/MoEngage/browser.js
- packages/analytics-js-integrations/src/integrations/MoEngage/constants.js
- packages/analytics-js-integrations/src/integrations/MoEngage/nativeSdkLoader.js
- packages/analytics-js-integrations/src/integrations/MoEngage/utils.js
This pull request introduces significant enhancements to the MoEngage integration in the `analytics-js-integrations` package. The changes focus on improving session management, user identification, event tracking, and SDK initialization, while adhering to MoEngage's official conventions. Additionally, the pull request includes refactoring for better modularity and maintainability.
* [`packages/analytics-js-integrations/src/integrations/MoEngage/nativeSdkLoader.js`](diffhunk://#diff-7349780458687c3e68e5a378749515761b4b1df7e298258c946aa1b25f031beeL3-R89): Updated the `loadNativeSdk` function to dynamically load the MoEngage SDK based on the calculated data center, ensuring proper initialization and error handling.
* [`packages/analytics-js-integrations/src/integrations/MoEngage/utils.js`](di …
> feat: moengage identity resolution support
