rudderlabs/rudder-sdk-js

integrations/GA/browser.js
Theses changes allow for the `category` and `label` properties to be passed to the GA tracker, instead of populating all three of them with `rudderElement.message.event`. This brings consistency with the documentation and cloud version's behavior of the GA integration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/53)
=> Addresses issue #50: populate 'category' and 'label' fields in GA

integrations/GA/browser.js
Mainly fixes property access issue (`rudderElement.properties` instead of `rudderElement.message.properties`).
Also sets page title and URL from the values of the `properties` object passed to rudder instead of keeping just the default ones. This makes native sdk's behavior consistent with the cloud version. 
This PR does not contain updated dist files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/52)
=> Addresses issue #49: sets updated page data on GA tracker

integrations/GA/browser.js, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/139)
=> Ga name tracker ---> Production

integrations/FacebookPixel/browser.js
The FacebookPixel integration fails to submit "Purchase" events due to an undefined variable, `product`.
#188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/187)
=> product is not defined

README.md, analytics.js, utils/linker/base64decoder.js, utils/linker/crc32.js, utils/linker/index.js, utils/linker/userLib.js
> We have added a utility function to decode the "rudderstack" query param which is added by the AMP page on turning on the rudder linker in its AMP SDK. This "rudderstack" key is encrypted by the CRC32 algorithm along with a checksum in the following format: <version>*<checkSum>*<idName1>*<idValue1>*<idName2>*<idValue2>...
The utility helps to extract out that anonymous id as a "UTF8" string.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/189)
=> Adding Support for AMP Linker

integrations/Clevertap/browser.js, integrations/Clevertap/index.js, integrations/ScriptLoader.js, integrations/client_server_name.js, integrations/index.js, integrations/integration_cname.js, utils/utils.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/219)
=> onboarding clevertap

integrations/BingAds/browser.js
It'll work even when event (or el) is empty means when user simply calls "rudderanalytics.track();".
Also changed the name from event to payload.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/234)
=> Made changes for Event Label(or el) field.

integrations/AdobeAnalytics/browser.js, integrations/AdobeAnalytics/eCommHandle.js, integrations/AdobeAnalytics/heartbeatHandle.js, integrations/AdobeAnalytics/index.js, integrations/AdobeAnalytics/util.js, integrations/index.js, integrations/integration_cname.js, integrations/utils/commonUtils.js, tests/html/script-test.html
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/250)
=> Adobe Analytics

integrations/FacebookPixel/browser.js
> To fix the issue with `eventCustomProperties` on `buildPayLoad` method.
>
>When checking the `indexOf` against `eventCustomProperties` it will always return -1 since actually  it's an array of objects with `eventCustomProperties` prop and their values. 
>
>Problem is the loop would continue and user defined custom properties for "Standard Events custom properties" always get ignored. 
>
> <img src="https://user-images.githubusercontent.com/5405770/121843319-4154d880-ccf7-11eb-9a45-7d74fcd22dfb.png" width=500 />
> Fix [#253](https://github.com/rudderlabs/rudder-sdk-js/issues/253) 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/255)
=> Fix eventCustomProperties issue in FacebookPixel buildPayLoad method.

integrations/GA4/utils.js
The GA4 integration mutates the `rudderAnalaytics.track()` `properties` object, which impacts other integrations as well (e.g. Facebook Pixel). The rogue code does not appear to do anything (although it's always very hard to tell with mutations), so I have simply removed it.
> Fix [#273 ]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/274)
=> Fix GA4 mutation of track method properties

integrations/FacebookPixel/browser.js
> There was two `console log` inside Facebook Pixel script which caused unnecessary logs in clients sites. just replaced them with `logger.debug`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/324)
=> Replaces console.logs to logger.debug in FacebookPixel

dist/rudder-sdk-js/package.json, integrations/Amplitude/browser.js, package.json
Here we are adding support for segment like page event call. Before it we used to call the event with 'Viewed page ****' but now will call the event with 'Viewed ***** Page', if 'alterPageEventName' is set to true in options.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/369)
=> Feat: altering page event name

analytics.js, rollup.intgConfig.js, utils/constants.js
> Suffix added to identify individual integration scripts
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/377)
=> Suffix added to identify individual integration scripts

integrations/Posthog/browser.js
> Added persistence: "localStorage+cookie" in options set of init() and some minor formattings.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/413)
=> Bugfix Posthog : added 'persistence' field in options set in init()

analytics.js, dist/rudder-sdk-js/index.d.ts, integrations/Posthog/browser.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/418)
=> Production staging - > perf_improvements

integrations/Hotjar/browser.js
> add Hotjar events api in track
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/421)
=> Hotjar - Ability to send events in track

integrations/LaunchDarkly/browser.js, integrations/LaunchDarkly/index.js, integrations/LaunchDarkly/utils.js, integrations/client_server_name.js, integrations/index.js, integrations/integration_cname.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/410)
=> LaunchDarkly new integration

integrations/PinterestTag/propertyMappingConfig.js
This commit will remove checkout step completed from eventMapping as it is not same as Checkout in Pinterest.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/431)
=> Pinterest Tag eventMapping fix.

dist/rudder-sdk-js/index.d.ts
> ts declaration updated for apiObject
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/453)
=> ts declaration updated

utils/EventRepository.js, utils/storage/beaconQueue.js
- If sendBeacon is not available it will fallback to XHR
- change the data format from "application /json" to "text/plain" for sendBeacon.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/460)
=> beacon fallback added

analytics.js, utils/storage/storage.js
When storage is not available :
- Show a log error at the time of initialization.
- Throw error at `load()` call.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/467)
=> Storage is not available fix

analytics.js, dist/rudder-sdk-js/package.json, package-lock.json, package.json
> In the SDK, `rudderanalytics` variable on the browser window is assumed to be always an array. However, once the SDK is initialized, it would be pointing to the analytics object. If the SDK is loaded more than once, it would result in the following error:
```
Uncaught TypeError: ms.forEach is not a function
at rudder-analytics.min.js:1:114792
at rudder-analytics.min.js:1:115524
(anonymous) @ rudder-analytics.min.js:1
(anonymous) @ rudder-analytics.min.js:1
```
Therefore, added a fix to check for array type before executing the queued methods.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/478)
=> Bug Fix: Added array check for analytics object

integrations/FacebookPixel/browser.js
There is some discrepancy between cloud mode and device mode. The mapping in cloud mode is not the same in device mode. So updating those changes.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/481)
=> Removing discrepancy with cloud mode for Facebook_Pixel.

integrations/FacebookPixel/util.js, integrations/FacebookPixel/utils.js, utils/EventRepository.js
- Fixed util file name typo
- Prevented original timestamp being overridden by current timestamp
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/488)
=> FB util file renamed and fixed `originalTimestamp` override

analytics.js
Empty event names in the destination event filtering config prevents users from either blacklisting or whitelisting their events. 
Hence, removed the check for empty event names.
_Note: Currently, users cannot delete event names in the destination config once added. As a result, if a user accidentally clicks on "add new item" and saves the configuration, the event name will be stored as an empty string ("") in the database._
> 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/489)
=> Allow empty event names in device mode event filtering

integrations/FacebookPixel/utils.js
> In FB Pixel utils, added object validations to check for `traits`, `context.traits`, and `properties` on the `message` object before accessing the `event_id` field.
Without these changes, it was causing an exception, and events do not flow to any other destinations that are after the FB Pixel destination.
> 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/491)
=> FB Pixel: Added object validations in getEventId function

integrations/SnapPixel/browser.js, integrations/SnapPixel/util.js
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/496)
=> Snap Pixelfeature (enhancements): 

analytics.js, dist/rudder-sdk-js/index.d.ts, utils/storage/cookie.js, utils/storage/storage.js
> For the customers migrating from Segment, SDK will auto capture Segment’s anonymousID and set it as RS’s anonymousID.
- Added an option in the load call, `autoAssignAnonId`. If you set it to `segment`, it will auto capture the anonymousID if present in cookie or local storage.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/497)
=> Feature: Auto capture anonymous id 

utils/utils.js
> If more than one similar device mode destination is attached with a single JS source, SDK was filtering those destinations.
- Modified the logic to retain the configs of those destinations. 
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/508)
=> fix destination filter issue

analytics.js
> This feature will enable the SDK methods to be called before load.
- All the previously called methods will be pushed to the call stack after load in the same order.
- Ex: Say the call stack currently have [page, identify, load, track]. It will become [load, page, identify, track]
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/507)
=> Feature: Allow API calls before load

integrations/FacebookPixel/browser.js
Returns for no product_id is reverted. ( Tonal error )
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/518)
=> Fb Pixel: fb pixel returns reverted

analytics.js
> This PR is regarding the changes we made in ready API logic to align the behavior with Segment.
- If integrations are loaded or no integration is available for loading then execute the callbacks immediately 
- Else store the callbacks in an array that will be executed after loading completes.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/522)
=> Align Ready method's behaviour  

buildspec.staging.yaml
> Added a fix in the buildspec-staging.yml file so that map files do not override the min.js files and are copied separately.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/547)
=> Fix: Staging buildspec updated

analytics.js
> Added validation to ensure the constructor in integration is not undefined
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/568)
=> Fix: Added validation for constructor

utils/utils.js
> Added error handling for accessing dead object error in Firefox
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/567)
=> Fix: Accessing dead object error in Firefox

integrations/LaunchDarkly/browser.js, integrations/LaunchDarkly/utils.js
> This supports `options.integrations.LaunchDarkly.key` as an override of the `key` field sent to the LaunchDarkly JS API. This allows for anonymous users to have a shared key so that the autogenerated Rudderstack ID for anonymous users is not sent to LaunchDarkly, and therefore all anonymous users share the same key. This is an additive change.
> [LaunchDarkly JS SDK `key` API ](https://launchdarkly.github.io/js-client-sdk/interfaces/_launchdarkly_js_client_sdk_.lduser.html#key)
> Fix #569
> This originated with #570 but that was branched off of `develop`. This branches from `v1-staging`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/570)
=> Support LaunchDarkly anonymous users shared key

utils/RudderContext.js
> Added validation for regex matching so that if it returns a null, system will handle that.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/574)
=> Fix: Added validation for userAgent in brave browser

analytics.js
> Added error handling in case of source config fetch fails or returns an empty/no response.
> Fix [#1]() 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/582)
=> Fix: source config fetch error handled

integrations/LaunchDarkly/browser.js
> Sets the `anonymousUsersSharedKey` from the config
> #575 was the original PR but missed this line from #570 (which was branched from `develop` instead of `v1-staging`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/592)
=> Launchdarkly Fix

integrations/Amplitude/browser.js, integrations/BingAds/browser.js, integrations/Braze/browser.js, integrations/Chartbeat/browser.js, integrations/Comscore/browser.js, integrations/CustomerIO/browser.js, integrations/Drip/browser.js, integrations/Fullstory/browser.js, integrations/GoogleAds/browser.js, integrations/GoogleOptimize/browser.js, integrations/GoogleTagManager/browser.js, integrations/Heap/browser.js, integrations/Hotjar/browser.js, integrations/INTERCOM/browser.js, integrations/Kissmetrics/browser.js, integrations/Lytics/browser.js, integrations/Matomo/browser.js, integrations/Mixpanel/browser.js, integrations/MoEngage/browser.js, integrations/Pendo/browser.js, integrations/PinterestTag/browser.js, integrations/Posthog/browser.js, integrations/ProfitWell/browser.js, integrations/Qualtrics/browser.js, integrations/RedditPixel/browser.js, integrations/ScriptLoader.js, integrations/Sentry/utils.js, integrations/SnapPixel/browser.js, integrations/VWO/browser.js
> Dataset attribute syntax updated in scriptLoader as the previous syntax was not working in IE 10.
From `element.dataset.property=propertyValue` to `element.setAttribute("data-property","propertyValue")`.
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/598)
=> Fix: dataset attribute syntax updated in scriptLoader

rollup.config.js, rollup.intgConfig.js
Added options to the `terser` rollup plugin to remove all the comments in the minified output.
Earlier the documentation comments of `store-js` and `get-value` packages were getting added to the rollup output file.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/602)
=> chore(build): update terser plugin options for rollup

rollup.config.js, rollup.intgConfig.js
Added an option to filesize rollup plugin, which will help compare the size of the output b/w the previous and current build runs. Also, added another option to show the size of Brotli compressed SDK.
This will be helpful during development.
Example output:
```
analytics.js → dist/rudder-analytics.min.js...
┌─────────────────────────────────────────────────────────────┐
│                                                             │
│   Destination: dist/rudder-analytics.min.js                 │
│   Bundle Size:  115.14 KB (was 115.58 KB in last build)     │
│   Minified Size:  114.58 KB (was 114.97 KB in last build)   │
│   Gzipped Size:  36.95 KB (was 37.2 KB in last build)       │
|   Brotli size: 30.27 KB (was 31.87 KB in last build)        |
│ …
```
=> chore(build): update filesize rollup plugin options

integrations/INTERCOM/browser.js
We are adding support for avatar objects. As of now, we were sending an avatar as a string but it is an object.
Previously avatar was set as follows:
```
"avatar" : "https://example.org/128Wash.jpg"
```
After update:
```
"avatar": {
"type":"avatar",
"image_url": "https://example.org/128Wash.jpg"
}
```
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/605)
=> feature(Intercom):: Adding support of avatar and refactoring code.

buildspec.prod.yaml, buildspec.staging.yaml, package.json, rollup.config.js, rollup.intgConfig.js, rollupUtils.js, utils/utils.js
- Refactored rollup configuration files to extract common parts to a separate module.
- Added support for building "staging" SDKs (with a suffix).
- Fixed npm "clean" script to delete files recursively.
- Simplified the staging build spec file as a result of the above updates.
Auxilary updates:
- Fixed SDK URL matching logic in utils to support relative file paths.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/604)
=> refactor(build): rollup configuration files

analytics.js
Removed unwanted local function to simplify the code.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/608)
=> refactor: simplify the code

integrations/ConvertFlow/browser.js, integrations/ConvertFlow/constants.js, integrations/ConvertFlow/index.js, integrations/ConvertFlow/utils.js, integrations/client_server_name.js, integrations/index.js, integrations/integration_cname.js
> Onboarding new integration Convertflow Web-device mode 
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/611)
=> feature/new integration: Convertflow onboarding

integrations/SnapEngage/browser.js, integrations/SnapEngage/constants.js, integrations/SnapEngage/index.js, integrations/SnapEngage/util.js, integrations/client_server_name.js, integrations/index.js, integrations/integration_cname.js
> Onboarding SnapEngage
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/612)
=> feature(new integration): SnapEngage web Device mode integration onboarding

integrations/Mixpanel/browser.js
> Added a fix for MP config.consolidatedPageCalls.
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/622)
=> Bug fix for MP consolidatedPageCalls

analytics.js, dist/rudder-sdk-js/index.d.ts
The embedded version fof the site failed to use cookies, so it generates
new anonymous id. Fixing it.
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/610)
=> Add SameSite None to fix embedded version

integrations/INTERCOM/browser.js
We are removing the `flattenEventObject` function as we are using an existing util function.
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/639)
=> refactor(Intercom) : remove unwanted code

integrations/FacebookPixel/browser.js, integrations/GoogleAds/browser.js, integrations/RedditPixel/browser.js, integrations/SnapPixel/browser.js, integrations/utils/commonUtils.js
> Expose a mapping UI for the following ads destinations and support mapping event names to be set from the dashboard:
1. Google Ads
2. Reddit Pixel
3. Snap Pixel
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/643)
=> feat(integration): add common util function for mapping event names in ads destinations

integrations/LinkedInInsightTag/browser.js
> fixing the error message
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/656)
=> fix(integration): error message in LinkedIn Insight Tag

.size-limit.js, integrations/June/browser.js, integrations/June/index.js, utils/client_server_name.js, utils/config_to_integration_names.js, utils/integration_cname.js
> Onboarding June device mode destination
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/673)
=> feat(new integration): onboarding june device mode destination v1.1

integrations/Iterable/browser.js, integrations/Iterable/constants.js, integrations/Iterable/index.js, integrations/Iterable/utils.js, integrations/client_server_name.js, integrations/index.js, integrations/integration_cname.js
> Onboarding Iterable web device mode
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/670)
=> feat(new integration): Iterable - onboard integration

.size-limit.js, integrations/Iterable/index.js, utils/client_server_name.js, utils/config_to_integration_names.js, utils/integration_cname.js
> Iterable onboarding
> Add missing export for RockerBox
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/676)
=> feat(new integration): Iterable onboarding

.size-limit.js, integrations/YandexMetrica/index.js, utils/client_server_name.js, utils/config_to_integration_names.js, utils/integration_cname.js
>onbaording yandex_metrica
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/687)
=> feat/yandex_metirca: onbaording yandex_metrica

integrations/GA/browser.js
In GA destination we are only supporting the total. With this change, we are adding support of revenue along with the total for eCommerce events.
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/690)
=> fix(ga): adding support of revenue along with total.

integrations/Refiner/browser.js
- in group call if someone want to send an email for an account level then they will send in traits. basically what is happening is if we don't separate this then user level email value is replaced by an account level email. so to keep separate if we found email value in context.traits then we will send it at user level or else the email which is inside traits will be sent at account level.
- [ ✅] Bug fix (non-breaking change that fixes an issue)
> Fix [#1]() 
- [ ✅] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/699)
=> fix: refiner group call email conflicts issue

CODEOWNERS, README.md, dist/rudder-sdk-js/package.json, service-worker/index.d.ts, tests/chrome-extension/USAGE.md
Fix the exports and type definitions in package json for the npm package
> Fix [#1](https://github.com/rudderlabs/rudder-sdk-js/issues/695) 
[Notion task](https://www.notion.so/BUG-NPM-package-exports-are-missing-types-7baf9d707f24470fb18e00b1b1cead31)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/696)
=> fix(service-worker): fix npm package exports and types

CODEOWNERS, README.md, dist/rudder-sdk-js/package.json, service-worker/index.d.ts, tests/chrome-extension/USAGE.md
Back merge from production the hotfix for npm package exports and types
Fix https://github.com/rudderlabs/rudder-sdk-js/issues/695
[Notion task](https://www.notion.so/BUG-NPM-package-exports-are-missing-types-7baf9d707f24470fb18e00b1b1cead31)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/700)
=> fix(service-worker): fix npm package exports and types (#696)

integrations/PinterestTag/browser.js
> Previously any user-defined event was defaulted to "custom" event, now, we are sending back the exact event name, if no mapping is found. This will show up as "unknown" event in Pinterest dashboard
> Fix [#1]() 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/717)
=> enhancement [integration] :: pinterest tag user defined event support

analytics.js, integrations/AdobeAnalytics/constants.js, integrations/client_server_name.js, integrations/integration_cname.js, integrations/utils/commonUtils.js, utils/utils.js
Reverts rudderlabs/rudder-sdk-js#685
Due to the import structure differences b/w v1 and v1.1 SDK architectures, if the changes are directly pulled into v1.1 SDK, it incurs a heavy SDK size cost. Hence, for the time being, reverting the changes to redo the approach.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/725)
=> Revert "feat: add utility to generate integration common names automatically"

__tests__/utils/ObjectUtils.test.js, src/core/analytics.js, src/utils/ObjectUtils.js
Fixed edge case where nested object properties that hace an array of objects as values did not behave the same in lodash merge and ramda mergeDeepRight.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/745)
=> fix(core): replicate lodash merge behaviour with ramda

src/integrations/BingAds/browser.js
- Microsoft updated the syntax for the javascript UET tracking library. Ref [doc](https://help.ads.microsoft.com/#apex/ads/en/56916/2-500). So made changes in bind ads destination reflecting the same.
- Added support for tracking Event value, added event_value field in bing ads payload. Refer this [link](https://help.ads.microsoft.com/#apex/ads/en/56709/2/#exp33) for more info regarding event_value.
[Ticket link](https://www.notion.so/rudderstacks/Bing-Ads-Device-mode-debugging-ee8e3b11b53e4288b872de1c4e40506a)
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> fix(destination): updated bing ads syntax as per the updated Microsoft syntax

integrations/BingAds/browser.js
Added support for tracking Event value, added `event_value` field in bing ads payload. Refer this [link](https://help.ads.microsoft.com/#apex/ads/en/56709/2/#exp33) for more info regarding event_value.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/746)
=> feat: added event_value field in bing ads payload

package-lock.json, package.json, src/integrations/GA4/ECommerceEventConfig.js, src/integrations/GA4/browser.js, src/integrations/GA4/utils.js
related to github issue raised to support ga4 custom properties
Now we are sending custom properties sent by the user, in property and product level.
Only the below properties were getting mapped in items and event properties.
By this PR we are accommod
ating any other properties sent by the users along with these.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/750)
=> fix(destination): adding custom properties for ga4

.github/workflows/draft-new-release.yml
filter out v1 release tags from changelog generation
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/767)
=> ci: filter out v1 release tags from changelog generation

.github/workflows/deploy-npm.yml, .github/workflows/draft-new-release-v1.yml, .github/workflows/draft-new-release.yml, .github/workflows/publish-new-release-v1.yml, .github/workflows/publish-new-release.yml
Change the branch of the release annotated tag to be on production and not the release candidate.
Fix issue with slack notification message details missing after moving the action as a step in the release action instead of standalone post release create one.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/801)
=> ci: tag releases on producton branch instead of release, fix slack msg

src/integrations/GA4/ECommerceEventConfig.js
We are fixing sending price for supported events instead of total.
- product viewed
- product added
- product removed
- add to wishlist
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> fix: ga4- fix total to price for events

__tests__/integrations/FacebookPixel.test.js, __tests__/integrations/FacebookPixel/FacebookPixel.test.js, src/integrations/FacebookPixel/browser.js
Advanced matching condition was missed while deprecating identify call and moving userData capture from SDK initialization. Added that condition.
Our previous Identify implementation was:
```
identify(rudderElement) {
if (this.advancedMapping) {
let payload = {};
const traits = rudderElement.message.context
? rudderElement.message.context.traits
: undefined;
if (this.useUpdatedMapping) {
const reserve = [
'email',
'lastName',
'firstName',
'phone',
'external_id',
'city',
'birthday',
'gender',
'street',
'zip',
'country',
];
// this construcPayload will help to map the traits in the same way as cloud mode
payload = constructPayload(rudderElement.message, traitsMapper);
if (payload.external_id) {
payload.external_id = sha256(payload.external_id).toString();
}
// here we are sending other …
```
=> fix(integrations): facebook pixel advanced matching condition added

.github/workflows/deploy-staging-v1.yml, .github/workflows/deploy-staging.yml
Adding facility to use any feature branch as bugbash branch, and adding condition in github actions to add it to the staging CDN.
To enable the feature branch as a bugbash CDN, we need to create a git tag with `bugbash-<topic>` using command:
`git tag bugbash-<topic>`
`git push --tags`
[Ticket link](https://www.notion.so/rudderstacks/Adding-Action-For-Bugbash-CDN-bee3ddf2cb7a4de0ae05a44b609c4667)
- Chrome
>
- Firefox
>
- Safari
>
=> feat(bugbash): adding bugbash tag condition

src/utils/utils.js
In an attempt to fix uuid collisions, use crypto.getRandomValues to create random values used in uuid generation.
[Ticket link](https://www.notion.so/rudderstacks/Different-events-with-same-messageId-bbe169ffc3654869853ef142e1067811)
- Chrome
>
- Firefox
>
- Safari
>
=> fix: use uuid secure (using crypto) for supported browsers

__tests__/integrations/GoogleAds/utils.test.js, src/integrations/GoogleAds/browser.js, src/integrations/GoogleAds/utils.js
- for any event in google ads, we will check first for the new config values. if new config values are present then we will proceed with that else we will fall back to old config
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> fix: googleads config order

src/integrations/GA4/browser.js
- Adding the `send_to` parameter in gtag event call to ensure that event will only be sent to the GA4 property with the measurement id configured in webapp.
- send_to parameter helps in routing data to a patricular GA4 property when more than one instance/properties are loaded.
[Ticket link](https://www.notion.so/rudderstacks/GA4-Send-send_to-parameter-with-gtag-during-event-calls-d4b077c737004a5f86b1fd22eb756695)
- Chrome
>
- Firefox
>
- Safari
>
=> feat(ga4): add sent_to parameter in gtag event call

packages/npm/index.d.ts, src/core/analytics.js
A new load option added: `onLoaded` - This expects to be a function and will be executed once the SDK is done loading and before the device mode destinations start to load.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> feat: onLoaded callback option

__tests__/utils/clientHint.test.js, src/core/analytics.js, src/utils/clientHint.js, src/utils/constants.js
Depending on the load option user agent client hint info is added in the event context.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> feat: user agent client hint info added in context

__tests__/oneTrustCookieConsent.test.js, __tests__/utils/utils.test.js, src/core/analytics.js, src/features/core/cookieConsent/OneTrust/browser.js, src/utils/constants.js, src/utils/utils.js
If OneTrust is enabled and consent has been given, fetch the deny list and pass it down as context property.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> feat: onetrust for cloud mode events

packages/npm/index.d.ts
This PR fixes a TypeScript compilation error caused by the type definition
```typescript
onLoaded?: (any) => void;
```
which is interpreted as a parameter named `any`, rather than a parameter typed as `any`.
```
node_modules/rudder-sdk-js/index.d.ts(106,17): error TS7051: Parameter has a name but no type. Did you mean 'arg0: any'?
```
N/A
N/A
=> fix: name `onLoaded` callback parameter

.github/workflows/draft-new-release-v1.yml, .github/workflows/draft-new-release.yml
Attempt to resolve the issue with incorrect changelog generation in release drafts by fetching all commit history to ensure previous version tagged commit hash exists
[Ticket link](https://www.notion.so/rudderstacks/Fix-Changelog-generation-issue-7bce1f8bb53d4009acb82b755d6c2b51?pvs=4)
- Chrome
>
- Firefox
>
- Safari
>
=> ci: fetch all commit history in draft new release action

__tests__/integrations/FacebookPixel/FacebookPixel.test.js, src/integrations/FacebookPixel/browser.js, src/integrations/FacebookPixel/utils.js, src/integrations/GA4/browser.js
1. content_category passed as an array. Now passing it as comma(,) separated string.
2. content_type passed as an array. Now passing it as a string.
3. valueFieldIdentifier configured as `properties.value `in webapp but considering `properties.revenue` in the calculation. Now considering `properties.revenue/ properties.value` for backward compatibility.
4. Event-wise mapping changes mentioned [here](https://www.notion.so/rudderstacks/Following-E-commerce-spec-56ea62ac808c4ef880c0362b2288d2fa?pvs=4#5fe30a269f6941c6a6a139090517a0bf)
[Ticket link
](https://www.notion.so/rudderstacks/Facebook-Pixel-Ecomm-spec-fix-Device-mode-f9836b3b501040a9bdf8d1bed77dbb84)
- Chrome
>
- Firefox
>
- Safari
>
=> fix(fb pixel): ecomm

src/integrations/BingAds/browser.js
When multiple instances of bing tags are added to the same page, they all end up sharing the same global array(window.uetq). Thus all tags are fired using same tagID. Now by overriding the name of the global variable to tagId, multiple instances of UET tag can be supported in a same page.
Imp links:
https://help.ads.microsoft.com/#apex/3/en/56714/2
https://help.ads.microsoft.com/apex/index/3/en/56685
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> fix: support bingAds for multiple tagIds

__tests__/integrations/FacebookPixel/FacebookPixel.test.js, src/integrations/FacebookPixel/browser.js
Add value parameter in custom-mapped events.
[Ticket link](https://www.notion.so/rudderstacks/Facebook-pixel-missing-value-parameter-in-custom-mapped-event-78a621f5e7b84de58dfaf5e334ca1447)
- Chrome
>
- Firefox
>
- Safari
>
=> fix(fb_pixel): add value in mapped event

rollup-configs/rollup.utilities.js
Fixed the typo in the rollup configuration file without which the release stage is set to default.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> fix: bugsnag typo in rollup config

src/core/analytics.js
Move transformation handler initialization after dataplane URL is determined.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> chore: move transformation handler initialization

__tests__/utils/errorHandler.test.js, src/utils/errorHandler.js
Suppress global window errors that are not generated by the SDK
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> fix: suppress notifying unwanted errors to Bugsnag

.size-limit.js, __tests__/utils/preProcessQueue.test.js, src/core/analytics.js, src/utils/EventRepository.js, src/utils/PreProcessQueue.js, src/utils/constants.js
- this is a pr to delaying cloud mode events based on flag called `bufferDataPlaneEventsUntilReady`
- if that flag is enabled then we are buffering cloud mode events in local storage and waiting for device mode integrations to get loaded and post that processing events to cloud mode
- for buffering cloud mode events we are using Queue to store it in `localStorage`
- once device mode integrations are successfully loaded, we are processing buffered cloud mode events and sending it to server
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> feat: delaying cloud mode events based on flag provided in options

src/integrations/GA4/browser.js
- This pull request introduces important updates to enhance our GA4 integration in hybrid mode. It enables support for the Identify call for hybrid mode, allowing us to update the userId and user_properties accurately. Additionally, we have made adjustments to the handling of cookie prefixes to ensure they are added only when necessary.
Key Changes:
1. Support for Identify call for hybrid mode: With this update, we can now utilize the Identify call to modify and synchronize the userId and user_properties between our system and GA4 in hybrid mode. This will provide more accurate and consistent tracking of user behavior and attributes.
2. Conditional addition of cookie prefix: We have introduced a new condition to add the cookie prefix selectively. The cookie prefix will only be applied …
=> feat(ga4): added identify call support for hybrid mode connection

packages/analytics-js/__tests__/components/eventManager/RudderEventFactory.test.ts, packages/analytics-js/__tests__/components/eventManager/utilities.test.ts, packages/analytics-js/src/components/eventManager/types.ts, packages/analytics-js/src/components/eventManager/utilities.ts, packages/analytics-js/src/components/eventRepository/EventRepository.ts
- Set default value `null` for `event` and `properties` fields.
- Used the mutated event from the data plane events queue for event callback invocation.
https://www.notion.so/rudderstacks/Fix-event-structure-JS-SDK-v3-6aeadd6ee4824420b0f2d1fdc15b45fe?pvs=4
- Chrome
>
- Firefox
>
- Safari
>
=> fix: issues in rudder event structure

src/core/analytics.js, src/utils/constants.js
- This pull request introduces a new flag, dataPlaneEventsBufferTimeout, which allows users to specify the maximum buffering time for data plane events. If no value is provided and bufferDataPlaneEventsUntilReady is set to true, the default timeout value of 10 seconds will be used.
- The dataPlaneEventsBufferTimeout flag accepts a numerical value representing the timeout duration in milliseconds. This enhancement provides customers with greater control over timeout values, allowing them to customize it according to their specific needs.
- By introducing this flexibility, users can effectively manage the buffering duration for data plane events and optimize their system's performance.
Ticket link
- …
=> feat: introduce flexible configuration for maximum buffering time of data plane events

src/integrations/GA4/browser.js
- In this PR, we have introduced a new feature to support user_properties as a part of the init call. Previously, user_properties were being set as a part of the gtag object. However, we encountered a limitation where the gtag object would get wiped clean on every page load, meaning that user_traits were not stored in gtag cookies or storage. Consequently, users were required to manually call an identify function on every page load.
- To address this issue, we have implemented a solution that includes setting user_properties as a part of the init call. This enhancement allows us to automatically set the existing user_properties as a part of the gtag object on each page load without the need for an explicit identify call.
- By incorporating user_properties in the init call, we improve the …
=> feat(ga4): support of user_properties as a part of init call

package-lock.json, sanity-suite/__mocks__/identify8.json, sanity-suite/package-lock.json, sanity-suite/package.json, sanity-suite/src/testBookSuites/identify.js, src/core/analytics.js
normalise userId before comparing with existing (if any) in identify call
[Ticket link](https://www.notion.so/rudderstacks/Ensure-userId-in-identify-call-is-always-evaluated-as-string-when-used-e872975aa8204326a0f926f4bb9cb508?pvs=4)
- Chrome
>
- Firefox
>
- Safari
>
=> fix: transform to string any userId passed as number in identify calls

.github/workflows/deploy-beta.yml
Allow deplyment of bugbash tags also as beta to their own cdn folders to enable multible bugbash on the same time.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> ci: enable bugbash tag deployment via github action

src/core/analytics.js
Fixed the bug that was incorrectly checking the `typeof` value of the prototype during destination SDK load check.
https://www.notion.so/rudderstacks/Bug-Destination-SDK-load-check-incorrectly-uses-typeof-in-the-conditional-statement-SDK-f43183362c9440ba9b8d1f67122affa3?pvs=4
- Chrome
>
- Firefox
>
- Safari
>
=> fix: destination sdk load check

packages/analytics-js/.size-limit.js, packages/analytics-js/__tests__/components/utilities/checks.test.ts, packages/analytics-js/__tests__/components/utilities/object.test.ts, packages/analytics-js/src/components/eventManager/utilities.ts, packages/analytics-js/src/components/utilities/checks.ts, packages/analytics-js/src/components/utilities/loadOptions.ts, packages/analytics-js/src/components/utilities/object.ts, packages/analytics-js/src/services/StoreManager/StoreManager.ts, packages/analytics-js/src/services/StoreManager/storages/CookieStorage.ts, packages/analytics-js/src/services/StoreManager/storages/InMemoryStorage.ts, packages/analytics-js/src/services/StoreManager/storages/LocalStorage.ts
- Fixed issues with storage options configuration where undefined values from state were taking precedence.
- Removed undefined and null values from certain load option values.
https://www.notion.so/rudderstacks/Bug-Cookies-are-not-stored-on-the-top-domain-V3-9f8120e98f18484b841132258b7f210d?pvs=4
- Chrome
>
- Firefox
>
- Safari
>
=> fix: storage option configuration

packages/analytics-js-plugins/src/deviceModeDestinations/index.ts
The error handler incorrectly rethrows the error when the destination ready check times out. Instead, the error is now logged and failed status updated to the state.
[Ticket link](https://www.notion.so/rudderstacks/Bug-Destination-ready-check-timeout-results-in-unhandled-error-in-async-context-JS-SDK-v3-dbe98f963a904e79a01a4e0cf7a8b620?pvs=4)
- Chrome
>
- Firefox
>
- Safari
>
=> fix: error handler when destination ready check times out

src/integrations/Mixpanel/browser.js
Fix the mixpanel alias call ID ordering
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> fix(mixpanel): alias id ordering

__tests__/utils/errorHandler.test.js, package-lock.json, sanity-suite/package-lock.json, sanity-suite/package.json, sanity-suite/src/testBookSuites/sourceConfig.js, src/features/core/metrics/errorReporting/ErrorReportingService.js, src/features/core/metrics/errorReporting/providers/Bugsnag.js, src/utils/notifyError.js
Two issues with IE 11:
- sanity suite build was not transpiling imported code from out side sanity-suite folder
- the window.rudderanalytics.errorReporting was not allowed to be added in window.rudderanalytics object is not extensible anymore in npm builds. Using window.RudderStackGlobals that is used in v3 instead
[Ticket link](https://www.notion.so/rudderstacks/IE11-issues-0a236aa3e6c74266bec4901d54d04e53?pvs=4)
- Chrome
>
- Firefox
>
- Safari
>
=> fix: fix issue with error reporting global key in IE11 for npm package

src/integrations/CustomerIO/browser.js
Providing an option for user from config dashbaord to send page name or not in page event.
If not send customerIo automatically captures the page url and map it to the page name.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> feat: enhancement: customerio option to send page name or not

.size-limit.js, src/integrations/Mixpanel/browser.js
For feature INT-163
- Removed the support of alias call when Simplified ID merge is selected.
- Removed the fallback value of anonymousId for `identify` calls since `alias` call is now removed. Mixpanel will take care of merging known users (userId) with anonymous users (deviceId) created by mixpanel sdk.
[Ticket link](https://www.notion.so/rudderstacks/Mixpanel-Simplified-ID-Merge-Device-Mode-dda27518bdfa4d08a1496b9c4466df11)
- Chrome
>
- Firefox
>
- Safari
>
=> feat: mixpanel simplified ID merge

package.json, packages/analytics-js-plugins/src/deviceModeDestinations/index.ts, packages/analytics-js/src/components/configManager/ConfigManager.ts, packages/analytics-js/src/components/core/Analytics.ts, packages/analytics-js/src/components/utilities/loadOptions.ts, packages/analytics-js/src/constants/logMessages.ts, packages/analytics-js/src/state/slices/loadOptions.ts
- Added missing validations for load options
- Fixed a bug where the load option `loadIntegrations` was not getting forwarded to the integrations.
- Added error handling for ready callbacks invocation.
https://linear.app/rudderstack/issue/SDK-150/dev-testing-for-v3-after-refactoring
- Chrome
>
- Firefox
>
- Safari
>
=> feat: add validations for load options

.size-limit.js, jest/jest.polyfills.js, src/core/analytics.js, src/utils/constants.js, src/utils/storage/storage.js, src/utils/storage/v3DecryptionUtils.js
Allowed decryption of v3 SDK encrypted cookies.
https://linear.app/rudderstack/issue/SDK-209/allow-v11-to-decrypt-stored-data-from-v3-encryption
- Chrome
>
- Firefox
>
- Safari
>
=> fix: persisted data decryption for v3

package.json
https://linear.app/rudderstack/issue/SDK-344/use-correct-flag-for-skipping-tags-during-releases
- Chrome
>
- Firefox
>
- Safari
>
=> chore: use correct flag for skipping tags for npm versioned releases

package.json
https://linear.app/rudderstack/issue/SDK-344/use-correct-flag-for-skipping-tags-during-releases
- Chrome
>
- Firefox
>
- Safari
>
=> chore: skip analytics v1.1 package during releases

packages/analytics-js-integrations/__tests__/integrations/LaunchDarkly/utils.test.js, packages/analytics-js-integrations/src/integrations/Amplitude/browser.js, packages/analytics-js-integrations/src/integrations/Amplitude/utils.js, packages/analytics-js-integrations/src/integrations/Iterable/utils.js, packages/analytics-js-integrations/src/integrations/LaunchDarkly/browser.js, packages/analytics-js-integrations/src/integrations/LaunchDarkly/utils.js, packages/analytics-js-integrations/src/integrations/Matomo/util.js, packages/analytics-js-integrations/src/integrations/Mouseflow/utils.js
Created utility to read destination-specific options from integrations object.
https://linear.app/rudderstack/issue/SDK-355/use-utility-to-read-destination-specific-options-from-integrations
- Chrome
>
- Firefox
>
- Safari
>
=> fix: use utility to determine destination specific integration options

packages/analytics-js/src/services/Logger/Logger.ts
As `console.debug` is not supported in IE 10, I've added a check before calling the function.
https://linear.app/rudderstack/issue/SDK-374/fix-logger-to-forward-only-supported-calls-to-the-provider-js-sdk-v3
- Chrome
>
- Firefox
>
- Safari
>
=> fix: forward only supported calls to the log provider

src/integrations/Klaviyo/browser.js
- Add trim and lowercase of event name before mapping
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> fix: add trim & lowercase for klaviyo track event

packages/analytics-js-plugins/src/bugsnag/utils.ts, packages/analytics-js-plugins/src/deviceModeDestinations/utils.ts
Add a configuration flag in Bugsnag client initialization to stop sending network breadcrumbs to Bugsnag.
https://linear.app/rudderstack/issue/SDK-375/stop-sending-network-breadcrumbs-to-bugsnag-js-sdk-v3
- Chrome
>
- Firefox
>
- Safari
>
=> fix: stop sending network breadcrumbs to bugsnag

packages/analytics-js/__tests__/services/StoreManager/component-cookie/index.test.ts, packages/analytics-js/src/constants/logMessages.ts, packages/analytics-js/src/services/StoreManager/component-cookie/index.ts, packages/analytics-js/src/services/StoreManager/storages/CookieStorage.ts
Added error handling around cookie data encoding.
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> fix: handle errors for cookies data URI encode and decode

src/integrations/Hotjar/browser.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> fix(hotjar): event.replaceAll is not a function

src/integrations/Sendinblue/browser.js
Resolves INT-451
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> chore(sendinblue): improve error message

.size-limit.js, __tests__/integrations/TikTokAds/tiktokads.test.js, src/integrations/TiktokAds/constants.js
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> feat(INT-580): messageId to event_id mapping support

.size-limit.js, src/integrations/GA4/utils.js
- fixed bugsnag alert related to GA4
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> fix(INT-580): object.formEntries is not a function

src/integrations/CustomerIO/browser.js, src/integrations/CustomerIO/nativeSdkLoader.js
Previously we were having a flag to check if datacenter is EU but now we are going with a drop down menu to select available datacenter from and falling back to previous flag in case new one is not available
Ticket link
- Chrome
>
- Firefox
>
- Safari
>
=> fix(INT-523): replaced flag with dropdown for datacenter selection

.github/workflows/deploy-prod-v3.yml, package.json, packages/analytics-js-common/project.json, packages/analytics-js-integrations/project.json, packages/analytics-js-plugins/project.json, packages/analytics-js-service-worker/project.json, packages/analytics-js/project.json, packages/analytics-v1.1/project.json, packages/loading-scripts/project.json, packages/sanity-suite/project.json
Make develop ready to deploy v1.1 CDN and npm package
Resolves [SDK-471](https://linear.app/rudderstack/issue/SDK-471/deprecate-old-branches-and-have-v11-and-v3-release-done-from-monorepo)
- Chrome
>
- Firefox
>
- Safari
>
=> ci(monorepo): prepare to release v1.1 from develop/main branches

packages/analytics-js/__tests__/components/core/Analytics.test.ts, packages/analytics-js/src/components/pluginsManager/PluginsManager.ts
Do not allow analytics to skip sending cloud mode events.
[Linear task link](https://linear.app/rudderstack/issue/SDK-619/make-either-of-xhr-or-beacon-plugins-mandatory)
=> fix(analytics-js): enforce default cloud mode events delivery plugin

.github/workflows/build-and-quality-checks-v3.yml, .github/workflows/deploy-beta-v3.yml, .github/workflows/deploy-dev-v3.yml, .github/workflows/deploy-npm-v3.yml, .github/workflows/deploy-prod-v3.yml, .github/workflows/deploy-sanity-suite.yml, .github/workflows/deploy-staging-v3.yml, .github/workflows/publish-new-release-v3.yml, .github/workflows/rollback-v3.yml, .github/workflows/test-v3.yml
use self hosted github runners
[Linear task link](https://linear.app/rudderstack/issue/SDK-678/use-hosted-github-runner-with-more-cores-to-speed-up-builds)
=> ci(monorepo): use self hosted github runner

packages/analytics-js/__fixtures__/fixtures.ts, packages/analytics-js/__tests__/components/userSessionManager/userSessionManager.test.ts, packages/analytics-js/src/components/userSessionManager/UserSessionManager.ts
https://linear.app/rudderstack/issue/SDK-738/fix-empty-anonymousid-after-reset-call
=> fix: empty anonymous id after reset call

.github/workflows/deploy-beta-v3.yml, .github/workflows/deploy-dev-v3.yml, .github/workflows/deploy-npm-v3.yml, .github/workflows/deploy-prod-v3.yml, .github/workflows/deploy-sanity-suite.yml, .github/workflows/deploy-staging-v3.yml, .github/workflows/publish-new-release-v3.yml, .github/workflows/rollback-v3.yml, packages/analytics-js-service-worker/project.json
Use default github runners as our organisation self-hosted does not have aws cli.
=> ci(monorepo): fix github runners for deploy actions

packages/analytics-js-common/__tests__/utilities/timezone.test.ts, packages/analytics-js-common/src/types/ApplicationState.ts, packages/analytics-js-common/src/types/Event.ts, packages/analytics-js-common/src/utilities/index.ts, packages/analytics-js-common/src/utilities/timezone.ts, packages/analytics-js/__tests__/components/eventManager/utilities.test.ts, packages/analytics-js/src/components/capabilitiesManager/CapabilitiesManager.ts, packages/analytics-js/src/components/eventManager/utilities.ts, packages/analytics-js/src/state/slices/context.ts, packages/analytics-v1.1/src/utils/RudderContext.js
- Auto capture timezone and attach it to event context for v1.1 and v3.
- Following the same format as mobile. Example: "GMT+0530"
=> feat: auto capture timezone as a part of context

examples/nextjs/hooks/sample-app/src/app/useRudderAnalytics.ts, examples/nextjs/js/sample-app/src/app/page.js, examples/nextjs/page-router/sample-app/src/useRudderAnalytics.ts, examples/nextjs/ts/sample-app/src/app/page.tsx, packages/analytics-js-plugins/rollup.config.mjs, packages/analytics-js/rollup.config.mjs, packages/sanity-suite/rollup.config.mjs, packages/sanity-suite/src/index-npm.ts, patches/@originjs+vite-plugin-federation+1.3.2.patch
Allow the remote imports for federated modules to work when the SDK is used in an app that uses webpack as bundler
[Linear task link](https://linear.app/rudderstack/issue/SDK-629/modern-bundling-does-not-work-with-webpack)
=> fix(analytics-js): fix remote import error when imported with webpack

packages/analytics-js/__tests__/components/userSessionManager/UserSessionManager.test.ts, packages/analytics-js/src/components/userSessionManager/UserSessionManager.ts
https://linear.app/rudderstack/issue/SDK-822/storage-migration-skips-empty-entries-leading-to-unwanted-errors-on
=> fix: storage migration to allow empty string values

packages/analytics-js-integrations/__tests__/integrations/FacebookPixel/utils.test.js, packages/analytics-js-integrations/src/integrations/FacebookPixel/browser.js, packages/analytics-js-integrations/src/integrations/FacebookPixel/utils.js
Send delivery_category as part of contents for Purchase(Order completed) event
=> feat: update tests and send delivery_category as part of contents for Purchase event

packages/analytics-v1.1/__tests__/ketchConsent.test.js, packages/analytics-v1.1/__tests__/oneTrustCookieConsent.test.js, packages/analytics-v1.1/src/core/analytics.js, packages/analytics-v1.1/src/features/core/cookieConsent/OneTrust/browser.js, packages/analytics-v1.1/src/features/core/cookieConsent/ketch/browser.js, packages/sanity-suite/rollup.config.mjs, packages/sanity-suite/src/ignoredProperties/ignoredProperties.js
Added additional consent management fields into `context.consentManagement` in the event object.
https://linear.app/rudderstack/issue/SDK-848/add-gcm-fields-in-events-context-for-v11-sdk
=> feat(analytics-js): add additional consent management fields

packages/analytics-js/__tests__/components/core/Analytics.test.ts, packages/analytics-js/src/components/core/Analytics.ts
Ready callbacks registered post the SDK ready state are not fired. So, this issue has been fixed.
https://linear.app/rudderstack/issue/SDK-1020/fix-the-sdk-post-ready-callback-execution
=> fix(analytics-js): post ready callback invocations

packages/analytics-js-plugins/rollup.config.mjs, packages/analytics-js-plugins/src/bugsnag/constants.ts, packages/analytics-js-plugins/src/bugsnag/index.ts, packages/analytics-js-plugins/src/bugsnag/logMessages.ts, packages/analytics-js/package.json, packages/analytics-js/rollup.config.mjs, packages/analytics-js/src/components/capabilitiesManager/polyfill/index.ts, packages/analytics-v1.1/package.json, packages/analytics-v1.1/rollup-configs/rollup.sdk.npm.mjs, packages/analytics-v1.1/rollup-configs/rollup.utilities.mjs, packages/analytics-v1.1/src/core/analytics.js, packages/analytics-v1.1/src/features/core/metrics/errorReporting/providers/Bugsnag.js, packages/analytics-v1.1/src/utils/constants.js
Provide new export alias for Chrome Extension content script usage in order to avoid any violations regarding third party script import during chome extension store approval.
Resolves [SDK-1002](https://linear.app/rudderstack/issue/SDK-1002/chrome-extension-store-approval-fails-with-violations-for-third-party)
=> fix(analytics-js): exclude third party host scripts from content scripts

packages/analytics-js-integrations/__tests__/integrations/Sprig/browser.test.js, packages/analytics-js-integrations/src/integrations/Sprig/browser.js, packages/analytics-js-integrations/src/integrations/Sprig/nativeSdkLoader.js
- In the quest for greater clarity and adherence to Spring Cloud conventions, this PR addresses the naming conflict between apiKey used in device mode and apiKey utilized in the new Spring Cloud mode.
- Renamed apiKey used in device mode to environmentId for enhanced differentiation.
- Retained the name apiKey for usage in Spring Cloud mode, aligning with Spring documentation for consistency and clarity.
- name convention are more suitable as per sprig docs
=> chore: changed sprig key name apiKey to environmentId

packages/analytics-js-integrations/__tests__/integrations/TikTokAds/tiktokads.test.js, packages/analytics-js-integrations/src/integrations/TiktokAds/browser.js
Resolves INT-1197
For custom events we are lowering their event name but we should retain the message event case as these are case sensitive at tiktok side
=> fix: tiktok remove lowercasing for custom events

packages/analytics-js-integrations/__tests__/integrations/Amplitude/amplitude.test.js, packages/analytics-js-integrations/src/integrations/Amplitude/browser.js, packages/analytics-js-integrations/src/integrations/Amplitude/utils.js
Adding support for [Amplitude unset field ](https://www.docs.developers.amplitude.com/analytics/apis/http-v2-api/#keys-for-the-event-argument:~:text=exceed%2040%20layers.-,user_properties,-Optional.%20Object.%20A)through Rudderstack Integration Object
Resolves INT-950
=> feat: amplitude add support for unset

packages/analytics-v1.1/__tests__/utils/utils.test.js, packages/analytics-v1.1/src/core/analytics.js, packages/analytics-v1.1/src/utils/utils.js, packages/sanity-suite/rollup.config.mjs
Added the missing query parameter lock integrations version to the source config URL.
https://linear.app/rudderstack/issue/SDK-1058/add-integrationversionlock-in-sourceconfig-query-param-for-v11
=> feat(analytics-v1.1): add lock integrations version as query param in source config url

package-lock.json, package.json
Upgraded the `rollup-plugin-serve` package to avoid the issue appearing while serving the HTML file with the SDK build.
[Linear task link](https://linear.app/rudderstack/issue/SDK-1161/fix-rollup-plugin-serve-issue)
=> chore: upgrade rollup-plugin-serve to fix serve issue

packages/analytics-js-integrations/__tests__/integrations/Amplitude/browser.test.js, packages/analytics-js-integrations/__tests__/integrations/Amplitude/util.test.js, packages/analytics-js-integrations/src/integrations/Amplitude/browser.js, packages/analytics-js-integrations/src/integrations/Amplitude/utils.js
Adding proxy server url config for amplitude. 
ref : https://www.docs.developers.amplitude.com/analytics/domain-proxy/
resolves INT-1016
[Linear task link](https://linear.app/rudderstack/issue/INT-1016/amplitude-in-device-mode-proxy-the-events-delivery-via-customer)
=> feat: adding proxy server url for amplitude

.github/workflows/build-and-quality-checks-v3.yml, examples/angular/sample-app/src/app/app.component.ts, examples/gatsby/sample-gatsby-site/src/pages/index.tsx, examples/nextjs/hooks/sample-app/src/app/useRudderAnalytics.ts, examples/nextjs/js/sample-app/src/app/page.js, examples/nextjs/page-router/sample-app/src/useRudderAnalytics.ts, examples/nextjs/ts/sample-app/src/app/page.tsx, examples/reactjs/hooks/sample-app/src/useRudderAnalytics.ts, examples/reactjs/js/sample-app/src/App.js, examples/reactjs/ts/sample-app/src/App.tsx, examples/reactjs/vite/sample-app/src/App.tsx, examples/symfony/sample/assets/app.js, examples/v3-beacon/index.html, examples/v3-legacy-minimum-plugins/index.html, examples/v3-legacy/index.html, examples/v3-minimum-plugins/index.html, examples/v3/index.html, packages/analytics-js/__tests__/app/RudderAnalytics.test.ts, packages/analytics-js/public/index-legacy-only.html, packages/analytics-js/public/index.html, packages/analytics-js/src/app/RudderAnalytics.ts, packages/sanity-suite/src/index-npm.ts
Users have issues remembering to assign new Rudderanalytics instances to window.rudderanalytics. This change will auto assign the object.
[Linear task link](https://linear.app/rudderstack/issue/SDK-1057/auto-assign-rudderanalytics-instance-to-global-object-in-constructor)
=> feat(analytics-js): auto expose new instance to window.rudderanalytics

packages/analytics-js/src/state/slices/loadOptions.ts
Change the value of storage migrate loadOption to true to assist existing users migrate
[Linear task link](https://linear.app/rudderstack/issue/SDK-1208/set-storageencryptionmigrate-default-value-true)
=> feat(analytics-js): change default value of storage migrate flag to true

packages/analytics-js-integrations/src/integrations/RedditPixel/browser.js, packages/analytics-js-integrations/src/integrations/RedditPixel/nativeSdkLoader.js
Resolves INT-1549
Reddit recently updated their SDK with the following changes:
'advertiserId' has been replaced with 'pixelId'
https://github.com/reddit/reddit-gtm-template/pull/28
https://linear.app/rudderstack/issue/INT-1549/events-not-flowing-to-reddit-pixel-destination
=> fix: reddit pixel isLoaded

packages/analytics-js-common/src/constants/destDisplayNamesToFileNamesMap.ts, packages/analytics-js-common/src/constants/destinationNames.ts, packages/analytics-js-common/src/constants/integrations/CommandBar/constants.ts, packages/analytics-js-common/src/v1.1/utils/client_server_name.js, packages/analytics-js-common/src/v1.1/utils/config_to_integration_names.js, packages/analytics-js-common/src/v1.1/utils/integration_cname.js, packages/analytics-js-integrations/__tests__/integrations/CommandBar/browser.test.js, packages/analytics-js-integrations/src/integrations/CommandBar/browser.js, packages/analytics-js-integrations/src/integrations/CommandBar/index.js, packages/analytics-js-integrations/src/integrations/CommandBar/nativeSdkLoader.js, packages/analytics-js-integrations/src/integrations/index.js
Onboard new destination commandbar
CommandBar is device mode only destination supports two calls:
trackevent -> for event tracking -> mapped to rudderstack's track call
boot -> for user identification -> mapped to rudderstack's identify call
Resolves INT-1311
=> feat: onboard new destination commandbar

package-lock.json, package.json, packages/analytics-js/package.json, packages/analytics-v1.1/package.json
updated component-emitter to latest, supporting TS
[Linear task link](https://linear.app/rudderstack/issue/SDK-947/update-component-emitter-dependency)
=> fix(rudder-sdk-js): updated component-emitter to latest, supporting TS

examples/v3-beacon/index.html, examples/v3-legacy-minimum-plugins/index.html, examples/v3-legacy/index.html, examples/v3-minimum-plugins/index.html, examples/v3/index.html, packages/analytics-js/public/index-legacy-only.html, packages/analytics-js/public/index.html, packages/loading-scripts/src/index.ts, packages/sanity-suite/public/v1.1/index-cdn.html, packages/sanity-suite/public/v1.1/index-local.html, packages/sanity-suite/public/v1.1/index-npm.html, packages/sanity-suite/public/v1.1/integrations/index-cdn.html, packages/sanity-suite/public/v1.1/integrations/index-local.html, packages/sanity-suite/public/v1.1/integrations/index-npm.html, packages/sanity-suite/public/v1.1/manualLoadCall/index-cdn.html, packages/sanity-suite/public/v1.1/manualLoadCall/index-local.html, packages/sanity-suite/public/v1.1/manualLoadCall/index-npm.html, packages/sanity-suite/public/v3/index-cdn.html, packages/sanity-suite/public/v3/index-local.html, packages/sanity-suite/public/v3/index-npm.html, packages/sanity-suite/public/v3/integrations/index-cdn.html, packages/sanity-suite/public/v3/integrations/index-local.html, packages/sanity-suite/public/v3/integrations/index-npm.html, packages/sanity-suite/public/v3/manualLoadCall/index-cdn.html, packages/sanity-suite/public/v3/manualLoadCall/index-local.html, packages/sanity-suite/public/v3/manualLoadCall/index-npm.html
POlyfill io url returns empty file if version is not defined in the query params. It might be a glitch on their side or a breaking change they introduced.
To rectify IE11 loading, changed the loading snippet accordingly
[Linear task link](https://linear.app/rudderstack/issue/SDK-1392/js-sdk-snippet-ie11-polyfill-url-issue)
=> fix(analytics-js-loading-scripts): add version in polyfill io url

packages/analytics-js-plugins/__fixtures__/msw.handlers.js, packages/analytics-js-plugins/__tests__/bugsnag/utils.test.ts, packages/analytics-js/src/components/capabilitiesManager/detection/storage.ts
- log warning instead error when a storage capability is unavailable
- Fixed flaky test cases for bugsnag
=> refactor: log warning instead error when a storage capability is unavailable

packages/analytics-js-integrations/package.json, packages/analytics-js-plugins/package.json, packages/analytics-js-service-worker/package.json, packages/analytics-js/package.json
Added missing `typesVersions` declaration for older Typescript versions.
https://linear.app/rudderstack/issue/SDK-1456/add-typeversions-declaration-in-analytics-js-package-to-support
=> chore: add typesVersions declaration

packages/analytics-js-integrations/src/integrations/CommandBar/nativeSdkLoader.js
=> fix: remove pollyfill url from command bar destination

packages/analytics-js-common/src/constants/integrations/destDisplayNamesToFileNamesMap.ts, packages/analytics-js-common/src/constants/integrations/destinationNames.ts
Added missing XPixel name mapping.
https://linear.app/rudderstack/issue/INT-2798/[fix]-xpixel-name-mapping-in-js-sdk
=> fix: add xpixel missing name mapping

packages/analytics-js-integrations/__tests__/integrations/Braze/browser.test.js, packages/analytics-js-integrations/src/integrations/Braze/browser.js
**Problem:**
Customers were experiencing "Braze SDK Error: sdkMetadata contained an invalid value" specifically in HYBRID mode. The error occurred due to a timing issue where  addSdkMetadata was called immediately after SDK initialization, before the Braze SDK was fully loaded.
**Root Cause:**
Race Condition:  addSdkMetadata was called in init() before the SDK finished loading
Timing Issue: The SDK's validation logic wasn't ready when metadata was added
Hybrid Mode Visibility: Error was more noticeable in hybrid mode since other methods do minimal work
**Solution:**
Implemented an event-based approach that integrates with RudderStack's existing integration lifecycle:
**Key Changes:**
Moved metadata addition to isReady(): SDK metadata is now added when the integration becomes ready, …
=> fix: braze sdk init issue
